# Generated by NeuroStack
# Artifact: agent/testing_14


from __future__ import annotations

from google.adk import Agent
from google.genai import types

from .prompt import SYSTEM_PROMPT, AGENT_DESCRIPTION

import importlib.util as _ilu
import pathlib as _pl
_spec_database_server = _ilu.spec_from_file_location(
    'database_server',
    _pl.Path(__file__).parent.parent.parent / 'mcp_servers' / 'internal' / 'database_server.py',
)
_mod_database_server = _ilu.module_from_spec(_spec_database_server)
_spec_database_server.loader.exec_module(_mod_database_server)
database_server = _mod_database_server.create_mcp_server





# ============================================================================
# AGENT DEFINITION
# ============================================================================

testing_14 = Agent(
    name="testing_14",
    model='bedrock/us.anthropic.claude-sonnet-4-5-20250929-v1:0',
    description=AGENT_DESCRIPTION,
    instruction=SYSTEM_PROMPT,
    tools=[

        database_server(),
    ],
    generate_content_config=types.GenerateContentConfig(
        temperature=0.7,
        safety_settings=[
            types.SafetySetting(
                category=types.HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT,
                threshold=types.HarmBlockThreshold.OFF,
            ),
        ]
    ),
)

root_agent = testing_14
