# Generated by NeuroStack
# Artifact: agent/blog_updates_agent


from __future__ import annotations

from google.adk import Agent
from google.genai import types

from .prompt import SYSTEM_PROMPT, AGENT_DESCRIPTION

import importlib.util as _ilu
import pathlib as _pl
_spec_tools_write_formatted_blog = _ilu.spec_from_file_location(
    'write_formatted_blog',
    _pl.Path(__file__).parent.parent.parent / 'tools' / 'write_formatted_blog.py',
)
_mod_tools_write_formatted_blog = _ilu.module_from_spec(_spec_tools_write_formatted_blog)
_spec_tools_write_formatted_blog.loader.exec_module(_mod_tools_write_formatted_blog)
write_formatted_blog = _mod_tools_write_formatted_blog.write_formatted_blog





# ============================================================================
# AGENT DEFINITION
# ============================================================================

blog_updates_agent = Agent(
    name="blog_updates_agent",
    model='bedrock/us.anthropic.claude-sonnet-4-5-20250929-v1:0',
    description=AGENT_DESCRIPTION,
    instruction=SYSTEM_PROMPT,
    tools=[

        write_formatted_blog,
    ],
    generate_content_config=types.GenerateContentConfig(
        temperature=0.7,
        safety_settings=[
            types.SafetySetting(
                category=types.HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT,
                threshold=types.HarmBlockThreshold.OFF,
            ),
        ]
    ),
)

root_agent = blog_updates_agent
