# Generated by NeuroStack
# Artifact: agent/data_processing_agent


from __future__ import annotations

from google.adk import Agent
from google.genai import types

from .prompt import SYSTEM_PROMPT, AGENT_DESCRIPTION

import importlib.util as _ilu
import pathlib as _pl
_spec_tools_process_external_data = _ilu.spec_from_file_location(
    'process_external_data',
    _pl.Path(__file__).parent.parent.parent / 'tools' / 'process_external_data.py',
)
_mod_tools_process_external_data = _ilu.module_from_spec(_spec_tools_process_external_data)
_spec_tools_process_external_data.loader.exec_module(_mod_tools_process_external_data)
process_external_data = _mod_tools_process_external_data.process_external_data





# ============================================================================
# AGENT DEFINITION
# ============================================================================

data_processing_agent = Agent(
    name="data_processing_agent",
    model='bedrock/us.anthropic.claude-sonnet-4-5-20250929-v1:0',
    description=AGENT_DESCRIPTION,
    instruction=SYSTEM_PROMPT,
    tools=[

        process_external_data,
    ],
    generate_content_config=types.GenerateContentConfig(
        temperature=0.7,
        safety_settings=[
            types.SafetySetting(
                category=types.HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT,
                threshold=types.HarmBlockThreshold.OFF,
            ),
        ]
    ),
)

root_agent = data_processing_agent
