# Generated by NeuroStack
# Artifact: workflow/customer_support_workflow

"""
Workflow: customer_support_workflow
Description: Orchestrator workflow that delegates customer support tasks to specialized sub-agents.
Instructions: You are an orchestrator that coordinates sub-agents and delegates tasks appropriately.
"""
from __future__ import annotations
from google.adk import Agent
from google.genai import types

import importlib.util as _ilu
import pathlib as _pl
_spec_agents_customer_support_agent = _ilu.spec_from_file_location(
    'customer_support_agent',
    _pl.Path(__file__).parent.parent.parent / 'agents' / 'customer_support_agent' / 'agent.py',
)
_mod_agents_customer_support_agent = _ilu.module_from_spec(_spec_agents_customer_support_agent)
_spec_agents_customer_support_agent.loader.exec_module(_mod_agents_customer_support_agent)

customer_support_agent = _mod_agents_customer_support_agent.root_agent





root_agent = Agent(
    model='us.anthropic.claude-sonnet-4-5-20250929-v1:0',
    name="customer_support_workflow",
    description="""Orchestrator workflow that delegates customer support tasks to specialized sub-agents.""",
    instruction="""You are an orchestrator that coordinates sub-agents and delegates tasks appropriately.""",
    global_instruction="""You are an orchestrator that coordinates sub-agents and delegates tasks appropriately.""",
    sub_agents=[customer_support_agent],
    generate_content_config=types.GenerateContentConfig(
        safety_settings=[
            types.SafetySetting(
                category=types.HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT,
                threshold=types.HarmBlockThreshold.OFF,
            ),
        ]
    ),
    tools=[],
)
