# Generated by NeuroStack
# Artifact: workflow/customer_support_workflow

from __future__ import annotations
from google.adk.agents.sequential_agent import SequentialAgent

import importlib.util as _ilu
import pathlib as _pl
_spec_agents_customer_support_agent = _ilu.spec_from_file_location(
    'customer_support_agent',
    _pl.Path(__file__).parent.parent.parent / 'agents' / 'customer_support_agent' / 'agent.py',
)
_mod_agents_customer_support_agent = _ilu.module_from_spec(_spec_agents_customer_support_agent)
_spec_agents_customer_support_agent.loader.exec_module(_mod_agents_customer_support_agent)

customer_support_agent = _mod_agents_customer_support_agent.root_agent



root_agent = SequentialAgent(
    name="customer_support_workflow",
    description="""You are an orchestrator that coordinates sub-agents and delegates tasks appropriately.""",
    sub_agents=[customer_support_agent],
)
