# Generated by NeuroStack
# Artifact: agent/aaa


from __future__ import annotations

from google.adk import Agent
from google.genai import types

from .prompt import SYSTEM_PROMPT, AGENT_DESCRIPTION

import importlib.util as _ilu
import pathlib as _pl
_spec_tools_analyze_codebase_risks = _ilu.spec_from_file_location(
    'analyze_codebase_risks',
    _pl.Path(__file__).parent.parent.parent / 'tools' / 'analyze_codebase_risks.py',
)
_mod_tools_analyze_codebase_risks = _ilu.module_from_spec(_spec_tools_analyze_codebase_risks)
_spec_tools_analyze_codebase_risks.loader.exec_module(_mod_tools_analyze_codebase_risks)
analyze_codebase_risks = _mod_tools_analyze_codebase_risks.analyze_codebase_risks





# ============================================================================
# AGENT DEFINITION
# ============================================================================

aaa = Agent(
    name="aaa",
    model='bedrock/us.anthropic.claude-sonnet-4-5-20250929-v1:0',
    description=AGENT_DESCRIPTION,
    instruction=SYSTEM_PROMPT,
    tools=[

        analyze_codebase_risks,
    ],
    generate_content_config=types.GenerateContentConfig(
        temperature=0.7,
        safety_settings=[
            types.SafetySetting(
                category=types.HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT,
                threshold=types.HarmBlockThreshold.OFF,
            ),
        ]
    ),
)

root_agent = aaa
