# Generated by NeuroStack
# Artifact: workflow/workflow_testing

"""
Graph-Based Workflow: workflow_testing
Graph-based ADK workflow 'workflow_testing'

Auto-generated by the Graph Workflow Studio.
ADK Docs: https://adk.dev/graphs/routes/
          https://adk.dev/graphs/human-input/
"""
from __future__ import annotations
from dotenv import load_dotenv, find_dotenv
from google.adk import Agent, Workflow, Event, Context
import importlib.util as _ilu
import pathlib as _pl
_spec_agents_critic_agent = _ilu.spec_from_file_location(
    'critic_agent',
    _pl.Path(__file__).parent.parent.parent / 'agents' / 'critic_agent' / 'agent.py',
)
_mod_agents_critic_agent = _ilu.module_from_spec(_spec_agents_critic_agent)
_spec_agents_critic_agent.loader.exec_module(_mod_agents_critic_agent)
_spec_agents_writer_agent = _ilu.spec_from_file_location(
    'writer_agent',
    _pl.Path(__file__).parent.parent.parent / 'agents' / 'writer_agent' / 'agent.py',
)
_mod_agents_writer_agent = _ilu.module_from_spec(_spec_agents_writer_agent)
_spec_agents_writer_agent.loader.exec_module(_mod_agents_writer_agent)

critic_agent = _mod_agents_critic_agent.root_agent
writer_agent = _mod_agents_writer_agent.root_agent
from pydantic import BaseModel
from typing import Any
import os, re

load_dotenv(find_dotenv())


# ──────────────────────────────────────────────
# Pydantic Schemas
# ──────────────────────────────────────────────
# (No custom schemas)

# ──────────────────────────────────────────────
# Agent Definitions
# ──────────────────────────────────────────────
# (No agent nodes defined)

# ──────────────────────────────────────────────
# Join Nodes — Fan-in for parallel branches
# ──────────────────────────────────────────────
# (No join nodes)

# ──────────────────────────────────────────────
# Function Nodes — Plain Python (no LLM)
# ──────────────────────────────────────────────
# (No function nodes)

# ──────────────────────────────────────────────
# HITL Nodes — yield RequestInput(...) to pause for human input
# ──────────────────────────────────────────────
# (No HITL nodes)

# ──────────────────────────────────────────────
# Router Nodes — return Event(route=KEY) for conditional branching
# ──────────────────────────────────────────────
# (No router nodes)

# ──────────────────────────────────────────────
# Workflow Graph
# ──────────────────────────────────────────────
root_agent = Workflow(
    name="workflow_testing",
    edges=[
        ("START", writer_agent),
        (writer_agent, critic_agent),
        (critic_agent,),  # → END
    ]
)
