# Generated by NeuroStack
# Artifact: agent/testing_abcd

"""
System prompt for testing_abcd.
"""

AGENT_DESCRIPTION = """
this agent is being created for testing
"""

SYSTEM_PROMPT = """
this agent is being created for testing
"""
