# Generated by NeuroStack
# Vendored from platform origin: agent/hc_decision_triage_agent (upstream_version=platform)

"""hc_decision_triage_agent using Google ADK."""
from __future__ import annotations
from google.adk import Agent
from google.genai import types
import importlib.util as _ilu
import pathlib as _pl
_spec_rel_prompt = _ilu.spec_from_file_location(
    'prompt',
    _pl.Path(__file__).parent / 'prompt.py',
)
_mod_rel_prompt = _ilu.module_from_spec(_spec_rel_prompt)
_spec_rel_prompt.loader.exec_module(_mod_rel_prompt)

SYSTEM_PROMPT = _mod_rel_prompt.SYSTEM_PROMPT
def create_hc_decision_triage_agent() -> Agent:
    return Agent(
        name="hc_decision_triage_agent",
        model='bedrock/us.anthropic.claude-sonnet-4-5-20250929-v1:0',
        description="Analyzes clinical/healthcare security incidents and builds PHI-aware response plans.",
        instruction=SYSTEM_PROMPT,
        tools=[],
        generate_content_config=types.GenerateContentConfig(
            safety_settings=[types.SafetySetting(
                category=types.HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT,
                threshold=types.HarmBlockThreshold.OFF,
            )]
        ),
    )

hc_decision_triage_agent = create_hc_decision_triage_agent()
root_agent = hc_decision_triage_agent
