# Generated by NeuroStack
# Artifact: workflow/testing_65

"""
Graph-Based Workflow: testing_65
Graph-based ADK workflow 'testing_65'

Auto-generated by the Graph Workflow Studio.
ADK Docs: https://adk.dev/graphs/routes/
          https://adk.dev/graphs/human-input/
"""
from __future__ import annotations
from dotenv import load_dotenv, find_dotenv
from google.adk import Agent, Workflow, Event, Context
import importlib.util as _ilu
import pathlib as _pl
_spec_agents_ai_infrastructure_deployment_agent = _ilu.spec_from_file_location(
    'ai_infrastructure_deployment_agent',
    _pl.Path(__file__).parent.parent.parent / 'agents' / 'ai_infrastructure_deployment_agent' / 'agent.py',
)
_mod_agents_ai_infrastructure_deployment_agent = _ilu.module_from_spec(_spec_agents_ai_infrastructure_deployment_agent)
_spec_agents_ai_infrastructure_deployment_agent.loader.exec_module(_mod_agents_ai_infrastructure_deployment_agent)
_spec_agents_hc_decision_triage_agent = _ilu.spec_from_file_location(
    'hc_decision_triage_agent',
    _pl.Path(__file__).parent.parent.parent / 'agents' / 'hc_decision_triage_agent' / 'agent.py',
)
_mod_agents_hc_decision_triage_agent = _ilu.module_from_spec(_spec_agents_hc_decision_triage_agent)
_spec_agents_hc_decision_triage_agent.loader.exec_module(_mod_agents_hc_decision_triage_agent)

ai_infrastructure_deployment_agent = _mod_agents_ai_infrastructure_deployment_agent.root_agent
hc_decision_triage_agent = _mod_agents_hc_decision_triage_agent.root_agent
from pydantic import BaseModel
from typing import Any
import os, re

load_dotenv(find_dotenv())


# ──────────────────────────────────────────────
# Pydantic Schemas
# ──────────────────────────────────────────────
# (No custom schemas)

# ──────────────────────────────────────────────
# Agent Definitions
# ──────────────────────────────────────────────
# (No agent nodes defined)

# ──────────────────────────────────────────────
# Join Nodes — Fan-in for parallel branches
# ──────────────────────────────────────────────
# (No join nodes)

# ──────────────────────────────────────────────
# Function Nodes — Plain Python (no LLM)
# ──────────────────────────────────────────────
# (No function nodes)

# ──────────────────────────────────────────────
# HITL Nodes — yield RequestInput(...) to pause for human input
# ──────────────────────────────────────────────
# (No HITL nodes)

# ──────────────────────────────────────────────
# Router Nodes — return Event(route=KEY) for conditional branching
# ──────────────────────────────────────────────
# (No router nodes)

# ──────────────────────────────────────────────
# Workflow Graph
# ──────────────────────────────────────────────
root_agent = Workflow(
    name="testing_65",
    edges=[
        ("START", hc_decision_triage_agent),
        (ai_infrastructure_deployment_agent,),  # → END
    ]
)
