# Generated by NeuroStack
# Artifact: workflow/simple_test_workflow

"""
Graph-Based Workflow: simple_test_workflow
A minimal test workflow for testing agent creation and risk evaluation.

Auto-generated by the Graph Workflow Studio.
ADK Docs: https://adk.dev/graphs/routes/
          https://adk.dev/graphs/human-input/
"""
from __future__ import annotations
from dotenv import load_dotenv, find_dotenv
from google.adk import Agent, Workflow, Event, Context
from pydantic import BaseModel
from typing import Any
import os, re

load_dotenv(find_dotenv())


# ──────────────────────────────────────────────
# Pydantic Schemas
# ──────────────────────────────────────────────
# (No custom schemas)

# ──────────────────────────────────────────────
# Agent Definitions
# ──────────────────────────────────────────────
# Agent: Test Agent
test_agent = Agent(
    name="test_agent",
    model='bedrock/us.anthropic.claude-sonnet-4-5-20250929-v1:0',
    instruction="""You are a simple test agent. Your role is to acknowledge any input you receive and provide a brief, friendly response. Simply confirm that you've received the input and echo back a summary of what was provided to you."""
)

# ──────────────────────────────────────────────
# Join Nodes — Fan-in for parallel branches
# ──────────────────────────────────────────────
# (No join nodes)

# ──────────────────────────────────────────────
# Function Nodes — Plain Python (no LLM)
# ──────────────────────────────────────────────
# (No function nodes)

# ──────────────────────────────────────────────
# HITL Nodes — yield RequestInput(...) to pause for human input
# ──────────────────────────────────────────────
# (No HITL nodes)

# ──────────────────────────────────────────────
# Router Nodes — return Event(route=KEY) for conditional branching
# ──────────────────────────────────────────────
# (No router nodes)

# ──────────────────────────────────────────────
# Workflow Graph
# ──────────────────────────────────────────────
root_agent = Workflow(
    name="simple_test_workflow",
    edges=[
        ("START", test_agent),
        (test_agent,),  # → END
    ]
)
