# Generated by NeuroStack
# Artifact: agent/meeting_digest_agent


from __future__ import annotations

from google.adk import Agent
from google.genai import types

from .prompt import SYSTEM_PROMPT, AGENT_DESCRIPTION

import importlib.util as _ilu
import pathlib as _pl
_spec_tools_meeting_tools = _ilu.spec_from_file_location(
    'meeting_tools',
    _pl.Path(__file__).parent.parent.parent / 'tools' / 'meeting_tools.py',
)
_mod_tools_meeting_tools = _ilu.module_from_spec(_spec_tools_meeting_tools)
_spec_tools_meeting_tools.loader.exec_module(_mod_tools_meeting_tools)
summarize_meeting = _mod_tools_meeting_tools.summarize_meeting





# ============================================================================
# AGENT DEFINITION
# ============================================================================

meeting_digest_agent = Agent(
    name="meeting_digest_agent",
    model='bedrock/us.anthropic.claude-sonnet-4-5-20250929-v1:0',
    description=AGENT_DESCRIPTION,
    instruction=SYSTEM_PROMPT,
    tools=[

        summarize_meeting,
    ],
    generate_content_config=types.GenerateContentConfig(
        temperature=0.7,
        safety_settings=[
            types.SafetySetting(
                category=types.HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT,
                threshold=types.HarmBlockThreshold.OFF,
            ),
        ]
    ),
)

root_agent = meeting_digest_agent
