# Generated by NeuroStack
# Artifact: workflow/test_workflow_100

from __future__ import annotations
from google.adk.agents.sequential_agent import SequentialAgent

import importlib.util as _ilu
import pathlib as _pl
_spec_agents_critic_agent = _ilu.spec_from_file_location(
    'critic_agent',
    _pl.Path(__file__).parent.parent.parent / 'agents' / 'critic_agent' / 'agent.py',
)
_mod_agents_critic_agent = _ilu.module_from_spec(_spec_agents_critic_agent)
_spec_agents_critic_agent.loader.exec_module(_mod_agents_critic_agent)
_spec_agents_writer_agent = _ilu.spec_from_file_location(
    'writer_agent',
    _pl.Path(__file__).parent.parent.parent / 'agents' / 'writer_agent' / 'agent.py',
)
_mod_agents_writer_agent = _ilu.module_from_spec(_spec_agents_writer_agent)
_spec_agents_writer_agent.loader.exec_module(_mod_agents_writer_agent)

writer_agent = _mod_agents_writer_agent.root_agent
critic_agent = _mod_agents_critic_agent.root_agent



root_agent = SequentialAgent(
    name="test_workflow_100",
    description="""write using the writer agent and using the critic agent as well in sequential flow""",
    sub_agents=[writer_agent, critic_agent],
)
