# Generated by NeuroStack
# Artifact: workflow/high_risk_test_workflow

"""
Graph-Based Workflow: high_risk_test_workflow
High-risk test workflow with external data processing, human review gate, and action execution for testing Tier 3 risk evaluation.

Auto-generated by the Graph Workflow Studio.
ADK Docs: https://adk.dev/graphs/routes/
          https://adk.dev/graphs/human-input/
"""
from __future__ import annotations
from dotenv import load_dotenv, find_dotenv
from google.adk import Agent, Workflow, Event, Context
from google.adk import Context
from google.adk.events import RequestInput
from google.adk.workflow import node
from google.genai import types as genai_types
import importlib.util as _ilu
import pathlib as _pl
_spec_agents_data_processing_agent = _ilu.spec_from_file_location(
    'data_processing_agent',
    _pl.Path(__file__).parent.parent.parent / 'agents' / 'data_processing_agent' / 'agent.py',
)
_mod_agents_data_processing_agent = _ilu.module_from_spec(_spec_agents_data_processing_agent)
_spec_agents_data_processing_agent.loader.exec_module(_mod_agents_data_processing_agent)

data_processor = _mod_agents_data_processing_agent.root_agent
from pydantic import BaseModel
from pydantic import BaseModel, Field, model_validator
from typing import Any
import os, re

load_dotenv(find_dotenv())


# ──────────────────────────────────────────────
# Pydantic Schemas
# ──────────────────────────────────────────────
# (No custom schemas)

# ──────────────────────────────────────────────
# Agent Definitions
# ──────────────────────────────────────────────
# Agent: Action Agent
action_agent = Agent(
    name="action_agent",
    model='bedrock/us.anthropic.claude-sonnet-4-5-20250929-v1:0',
    instruction="""You are an action execution agent. Your role is to take the approved data from the review process and execute the final actions. Be precise and confirm what actions you are taking based on the approved input."""
)

# ──────────────────────────────────────────────
# Join Nodes — Fan-in for parallel branches
# ──────────────────────────────────────────────
# (No join nodes)

# ──────────────────────────────────────────────
# Function Nodes — Plain Python (no LLM)
# ──────────────────────────────────────────────
# (No function nodes)

# ──────────────────────────────────────────────
# HITL Nodes — yield RequestInput(...) to pause for human input
# ──────────────────────────────────────────────
_SKIP_PREFIXES = ("_adk", "__", "_", "temp:", "workflow_status")


class UserReviewFeedback(BaseModel):
    approved: bool = Field(description="True to approve the output, False to request revisions.")
    feedback: str = Field(
        default="",
        description="Required when declining — describe what should be changed.",
    )

    @model_validator(mode="after")
    def feedback_required_on_decline(self) -> "UserReviewFeedback":
        if not self.approved and not self.feedback.strip():
            raise ValueError("feedback is required when declining.")
        return self


def _extract_text_from_node_input(node_input) -> str:
    if node_input is None:
        return ""
    if isinstance(node_input, genai_types.Content):
        return "\n".join(
            part.text
            for part in (node_input.parts or [])
            if hasattr(part, "text") and part.text
        ).strip()
    if isinstance(node_input, str):
        return node_input.strip()
    if hasattr(node_input, "model_dump"):
        return str(node_input.model_dump())
    return str(node_input).strip()


def _is_internal_key(key: str) -> bool:
    return any(key.startswith(p) for p in _SKIP_PREFIXES)


def _build_review_body(ctx: Context) -> str:
    sections = []
    for key, value in ctx.state.to_dict().items():
        if _is_internal_key(key) or not value:
            continue
        lbl = key.replace("_", " ").title()
        text = str(value).strip()
        if text.startswith(("{", "[")) or "\n" in text:
            sections.append(f"### {lbl}\n{text}")
        else:
            sections.append(f"### {lbl}\n{text}")
    return (
        "\n\n".join(sections)
        if sections
        else "_No agent outputs found in session state._"
    )


def _make_text_event(text: str, state: dict | None = None) -> Event:
    return Event(
        output=text,
        content=genai_types.Content(
            role="model",
            parts=[genai_types.Part(text=text)],
        ),
        **({"state": state} if state else {}),
    )


def _parse_review_response(raw) -> UserReviewFeedback:
    import json as _json
    import logging as _logging
    if isinstance(raw, UserReviewFeedback):
        return raw
    if isinstance(raw, dict):
        try:
            return UserReviewFeedback.model_validate(raw)
        except Exception:
            pass
    if isinstance(raw, str):
        try:
            parsed = _json.loads(raw)
            if isinstance(parsed, dict):
                return UserReviewFeedback.model_validate(parsed)
        except Exception:
            pass
    if isinstance(raw, genai_types.Content):
        for part in (raw.parts or []):
            if hasattr(part, "function_response") and part.function_response:
                resp = part.function_response.response or {}
                if isinstance(resp, dict):
                    try:
                        return UserReviewFeedback.model_validate(resp)
                    except Exception:
                        pass
            if hasattr(part, "text") and part.text:
                try:
                    parsed = _json.loads(part.text)
                    if isinstance(parsed, dict):
                        return UserReviewFeedback.model_validate(parsed)
                except Exception:
                    pass
    _logging.getLogger(__name__).warning(
        "[human_review_gate] Could not parse resume_input (%s: %r). "
        "Defaulting to approved=True so the workflow can complete.",
        type(raw).__name__, raw,
    )
    return UserReviewFeedback(approved=True, feedback="")

@node(rerun_on_resume=True)
def human_review_gate(node_input, ctx: Context = None):
    """Human-in-the-Loop gate: Please review the processed data before proceeding with actions."""
    iteration = ctx.state.get("iterations_human_review_gate", 0) if ctx else 0
    interrupt_id = f"human_review_gate:iter{iteration}"
    resume_input = ctx.resume_inputs.get(interrupt_id) if ctx else None

    if not resume_input:
        last_output_text = _extract_text_from_node_input(node_input)
        if last_output_text:
            yield Event(state={"_hitl:last_output_human_review_gate": last_output_text})
        body = _build_review_body(ctx) if ctx else ""
        if "_No agent outputs found" in body:
            body = ""
        else:
            body = f"\n\n---\n### Session State\n{body}"

        review_content = f"### Output for Review\n{last_output_text}" if last_output_text else "_(No direct output received)_"
        msg = f"**[Review Cycle {iteration + 1} of 3]**\n\n{review_content}{body}\n\n---\nPlease review the processed data before proceeding with actions."
        yield RequestInput(message=msg, response_schema=UserReviewFeedback, interrupt_id=interrupt_id)
        return

    review_response = _parse_review_response(resume_input)
    if review_response.approved:
        last_output = ctx.state.get("_hitl:last_output_human_review_gate") or "_No output recorded._"
        # Route to next node via "approved" edge if wired; else workflow ends here.
        yield Event(
            output=last_output,
            content=genai_types.Content(
                role="model",
                parts=[genai_types.Part(text=last_output)],
            ),
            state={"workflow_status": "APPROVED"},
            route="approved",
        )
        return

    iterations = ctx.state.get("iterations_human_review_gate", 0) + 1
    if iterations > 3:
        last_output: str = ctx.state.get("_hitl:last_output_human_review_gate") or "_No output recorded._"
        # Route to next node via "approved" edge; forced approval due to max cycles.
        yield Event(
            output=last_output,
            content=genai_types.Content(
                role="model",
                parts=[genai_types.Part(text=last_output)],
            ),
            state={"workflow_status": "MAX_REVISIONS_REACHED"},
            route="approved",
        )
        return

    last_output_text = ctx.state.get(f"_hitl:last_output_human_review_gate") or "_No output recorded._"
    yield Event(
        content=genai_types.Content(
            role="user",
            parts=[genai_types.Part(
                text=(
                    "The user rejected your previous output. "
                    f"Please revise it based on this feedback:\n\n{review_response.feedback}\n\n"
                    "---\n### Your Previous Output\n\n"
                    f"{last_output_text}"
                )
            )],
        ),
        state={
            "iterations_human_review_gate": iterations,
            "feedback_human_review_gate": review_response.feedback,
        },
        route="revise",
    )

# ──────────────────────────────────────────────
# Router Nodes — return Event(route=KEY) for conditional branching
# ──────────────────────────────────────────────
# (No router nodes)

# ──────────────────────────────────────────────
# Workflow Graph
# ──────────────────────────────────────────────
root_agent = Workflow(
    name="high_risk_test_workflow",
    edges=[
        ("START", data_processor),
        (data_processor, human_review_gate),
        (human_review_gate,
            {
            "approved": action_agent,
            "revise": data_processor
            },
        ),
        (action_agent,),  # → END
    ]
)
