# Generated by NeuroStack
# Artifact: agent/ai_infrastructure_agent

"""
System prompt for ai_infrastructure_agent.
"""

AGENT_DESCRIPTION = """
Generates Infrastructure-as-Code for AI platform deployments
"""

SYSTEM_PROMPT = """
Generates Infrastructure-as-Code for AI platform deployments
"""
