# Generated by NeuroStack
# Vendored from platform origin: mcp/database_server (upstream_version=platform)

"""FastMCP toolset for database_server. Auto-generated."""
import sys
from pathlib import Path
from mcp.server.fastmcp import FastMCP
from typing import Dict, Any


mcp = FastMCP("database_server")

import importlib.util as _ilu
import pathlib as _pl
_spec_tools_database_tools = _ilu.spec_from_file_location(
    'database_tools',
    _pl.Path(__file__).parent.parent.parent / 'tools' / 'database_tools.py',
)
_mod_tools_database_tools = _ilu.module_from_spec(_spec_tools_database_tools)
_spec_tools_database_tools.loader.exec_module(_mod_tools_database_tools)

@mcp.tool()
async def execute_sql_query(db_path: str, sql_query: str) -> Dict[str, Any]:
    """MCP wrapper for execute_sql_query."""
    tool_execute_sql_query = _mod_tools_database_tools.execute_sql_query
    return tool_execute_sql_query(db_path, sql_query)

@mcp.tool()
async def fetch_data_from_table(db_path: str, table_name: str) -> Dict[str, Any]:
    """MCP wrapper for fetch_data_from_table."""
    tool_fetch_data_from_table = _mod_tools_database_tools.fetch_data_from_table
    return tool_fetch_data_from_table(db_path, table_name)

if __name__ == "__main__":
    mcp.run(transport="stdio")
