# Generated by NeuroStack
# Artifact: mcp/data.py

"""
FastMCP Server for data exposing selected tools.
Auto-generated by API at runtime.
"""

from mcp.server.fastmcp import FastMCP
from typing import Any, Dict, List, Optional

import importlib.util as _ilu
import pathlib as _pl
_spec_tools_enhanced_database_tools = _ilu.spec_from_file_location(
    'enhanced_database_tools',
    _pl.Path(__file__).parent.parent.parent / 'tools' / 'enhanced_database_tools.py',
)
_mod_tools_enhanced_database_tools = _ilu.module_from_spec(_spec_tools_enhanced_database_tools)
_spec_tools_enhanced_database_tools.loader.exec_module(_mod_tools_enhanced_database_tools)

tool_backup_database = _mod_tools_enhanced_database_tools.backup_database
tool_delete_stock_data = _mod_tools_enhanced_database_tools.delete_stock_data

mcp = FastMCP("data")


@mcp.tool()
async def backup_database(db_path: str, backup_path: str = None, include_timestamp: bool = True) -> Dict[str, Any]:
    """
    Auto-generated MCP tool wrapper for `backup_database`.
    Calls the `backup_database` tool from the `enhanced_database_tools` tool module.
    """
    return tool_backup_database(db_path=db_path, backup_path=backup_path, include_timestamp=include_timestamp)


@mcp.tool()
async def delete_stock_data(db_path: str, ticker: str = None, date_from: str = None, date_to: str = None, confirm: bool = False) -> Dict[str, Any]:
    """
    Auto-generated MCP tool wrapper for `delete_stock_data`.
    Calls the `delete_stock_data` tool from the `enhanced_database_tools` tool module.
    """
    return tool_delete_stock_data(db_path=db_path, ticker=ticker, date_from=date_from, date_to=date_to, confirm=confirm)


if __name__ == "__main__":
    mcp.run(transport="stdio")
