# Generated by NeuroStack
# Artifact: mcp/deployment_testing.py

"""
Server wrapper for deployment_testing MCP using MCPToolset.
Auto-generated by API at runtime.
"""

import sys
from pathlib import Path
from google.adk.tools.mcp_tool.mcp_toolset import MCPToolset, StdioConnectionParams
from mcp import StdioServerParameters

# A literal, not an environment lookup: generated server files must not ask for any
# permission of their own, or RiskGate reads every one of them as a new secret
# reference and sends it to Tier 3 for review.
AGENT_TIMEOUT = 180


def create_mcp_server() -> MCPToolset:
    """Create and return the MCPToolset for the 'deployment_testing' MCP."""
    toolset_script_path = str((Path(__file__).parent / "deployment_testing_toolset.py").resolve())
    return MCPToolset(
        connection_params=StdioConnectionParams(
            server_params=StdioServerParameters(
                command=sys.executable,
                args=[toolset_script_path],
            ),
            timeout=AGENT_TIMEOUT,
        )
    )
