# Generated by NeuroStack
# Artifact: mcp/deployment_testing.py

"""
FastMCP Server for deployment_testing exposing selected tools.
Auto-generated by API at runtime.
"""

from mcp.server.fastmcp import FastMCP
from typing import Any, Dict, List, Optional

import importlib.util as _ilu
import pathlib as _pl
_spec_tools_threat_hunting_timeline_tools = _ilu.spec_from_file_location(
    'threat_hunting_timeline_tools',
    _pl.Path(__file__).parent.parent.parent / 'tools' / 'threat_hunting_timeline_tools.py',
)
_mod_tools_threat_hunting_timeline_tools = _ilu.module_from_spec(_spec_tools_threat_hunting_timeline_tools)
_spec_tools_threat_hunting_timeline_tools.loader.exec_module(_mod_tools_threat_hunting_timeline_tools)

tool_build_timeline = _mod_tools_threat_hunting_timeline_tools.build_timeline
tool_group_into_episodes = _mod_tools_threat_hunting_timeline_tools.group_into_episodes
tool_summarize_episode = _mod_tools_threat_hunting_timeline_tools.summarize_episode

mcp = FastMCP("deployment_testing")


@mcp.tool()
async def build_timeline(collected: Dict[str, Any]) -> Dict[str, Any]:
    """
    Auto-generated MCP tool wrapper for `build_timeline`.
    Calls the `build_timeline` tool from the `threat_hunting_timeline_tools` tool module.
    """
    return tool_build_timeline(collected=collected)


@mcp.tool()
async def group_into_episodes(timeline_events: List[Dict[str, Any]], heuristics: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
    """
    Auto-generated MCP tool wrapper for `group_into_episodes`.
    Calls the `group_into_episodes` tool from the `threat_hunting_timeline_tools` tool module.
    """
    return tool_group_into_episodes(timeline_events=timeline_events, heuristics=heuristics)


@mcp.tool()
async def summarize_episode(episode: Dict[str, Any]) -> Dict[str, Any]:
    """
    Auto-generated MCP tool wrapper for `summarize_episode`.
    Calls the `summarize_episode` tool from the `threat_hunting_timeline_tools` tool module.
    """
    return tool_summarize_episode(episode=episode)


if __name__ == "__main__":
    mcp.run(transport="stdio")
