# Generated by NeuroStack
# Vendored from platform origin: mcp/support-ops-server (upstream_version=platform)

"""
FastMCP Server for support-ops-server exposing selected tools.
Auto-generated by API at runtime.
"""

import sys
from pathlib import Path
from mcp.server.fastmcp import FastMCP
from typing import Dict, Any, List



import importlib.util as _ilu
import pathlib as _pl
_spec_tools_classify_ticket_tools = _ilu.spec_from_file_location(
    'classify_ticket_tools',
    _pl.Path(__file__).parent.parent.parent / 'tools' / 'classify_ticket_tools.py',
)
_mod_tools_classify_ticket_tools = _ilu.module_from_spec(_spec_tools_classify_ticket_tools)
_spec_tools_classify_ticket_tools.loader.exec_module(_mod_tools_classify_ticket_tools)
_spec_tools_fetch_ticket_tools = _ilu.spec_from_file_location(
    'fetch_ticket_tools',
    _pl.Path(__file__).parent.parent.parent / 'tools' / 'fetch_ticket_tools.py',
)
_mod_tools_fetch_ticket_tools = _ilu.module_from_spec(_spec_tools_fetch_ticket_tools)
_spec_tools_fetch_ticket_tools.loader.exec_module(_mod_tools_fetch_ticket_tools)
_spec_tools_jira_tools = _ilu.spec_from_file_location(
    'jira_tools',
    _pl.Path(__file__).parent.parent.parent / 'tools' / 'jira_tools.py',
)
_mod_tools_jira_tools = _ilu.module_from_spec(_spec_tools_jira_tools)
_spec_tools_jira_tools.loader.exec_module(_mod_tools_jira_tools)
_spec_tools_search_kb_and_draft_response_tools = _ilu.spec_from_file_location(
    'search_kb_and_draft_response_tools',
    _pl.Path(__file__).parent.parent.parent / 'tools' / 'search_kb_and_draft_response_tools.py',
)
_mod_tools_search_kb_and_draft_response_tools = _ilu.module_from_spec(_spec_tools_search_kb_and_draft_response_tools)
_spec_tools_search_kb_and_draft_response_tools.loader.exec_module(_mod_tools_search_kb_and_draft_response_tools)

tool_classify_ticket = _mod_tools_classify_ticket_tools.classify_ticket
tool_fetch_ticket = _mod_tools_fetch_ticket_tools.fetch_ticket
tool_search_kb_and_draft_response = _mod_tools_search_kb_and_draft_response_tools.search_kb_and_draft_response
tool_update_jira_ticket = _mod_tools_jira_tools.update_jira_ticket

mcp = FastMCP("support-ops-server")


@mcp.tool()
async def fetch_ticket(ticket_id: str) -> Dict[str, Any]:
    """
    Retrieves a JIRA ticket by ID and returns relevant information.

    Args:
        ticket_id: The JIRA ticket ID (e.g. NS-10).
    """
    return tool_fetch_ticket(ticket_id)


@mcp.tool()
async def classify_ticket(text: str) -> Dict[str, Any]:
    """
    Classifies a support ticket by category, urgency, and confidence.

    Args:
        text: The ticket summary and/or description text to classify.
    """
    return tool_classify_ticket(text)


@mcp.tool()
async def search_kb_and_draft_response(
    ticket_summary: str,
    ticket_description: str,
    kb_results: List[Dict[str, str]],
    customer_name: str = "Customer",
) -> Dict[str, Any]:
    """
    Searches the knowledge base and drafts a response for the ticket.

    Args:
        ticket_summary: One-line summary of the ticket.
        ticket_description: Full description of the ticket.
        kb_results: List of KB articles (each a dict with 'title' and 'content').
        customer_name: Name of the customer to address in the response.
    """
    return tool_search_kb_and_draft_response(
        ticket_summary, ticket_description, kb_results, customer_name
    )


@mcp.tool()
async def update_jira_ticket(
    ticket_id: str,
    status: str,
    resolution_note: str,
    draft_response: str = "",
) -> Dict[str, Any]:
    """
    Posts a comment and transitions a JIRA ticket to resolved/escalated.

    Args:
        ticket_id: The JIRA ticket ID to update.
        status: Target status — 'resolved' or 'escalated'.
        resolution_note: Internal note explaining the action taken.
        draft_response: Customer-facing reply text (optional).
    """
    return tool_update_jira_ticket(ticket_id, status, resolution_note, draft_response)


if __name__ == "__main__":
    mcp.run(transport="stdio")
