# Generated by NeuroStack
# Artifact: tool/ado_board_tool.py

"""Azure DevOps board work item management tool.

Provides functions to create, read, update, and list work items on Azure DevOps boards.
Requires AZURE_DEVOPS_ORG, AZURE_DEVOPS_PROJECT, and AZURE_DEVOPS_PAT environment variables.
"""

import os
import base64
import json
from typing import Optional, List, Dict, Any

from dotenv import load_dotenv
import requests

# Load environment variables from .env file
load_dotenv(override=True)


def _get_ado_config() -> Dict[str, str]:
    """Get Azure DevOps configuration from environment variables.
    
    Returns:
        Dictionary with organization, project, base_url, and authorization header.
        
    Raises:
        ValueError: If required environment variables are not set.
    """
    organization = os.getenv('AZURE_DEVOPS_ORG')
    project = os.getenv('AZURE_DEVOPS_PROJECT')
    pat = os.getenv('AZURE_DEVOPS_PAT')
    
    if not all([organization, project, pat]):
        raise ValueError(
            "Required environment variables not set: "
            "AZURE_DEVOPS_ORG, AZURE_DEVOPS_PROJECT, AZURE_DEVOPS_PAT"
        )
    
    base_url = f"https://dev.azure.com/{organization}/{project}/_apis/wit/"
    authorization_header = base64.b64encode(f':{pat}'.encode('ascii')).decode('ascii')
    
    return {
        'organization': organization,
        'project': project,
        'base_url': base_url,
        'auth_header': authorization_header
    }


def create_ado_work_item(
    work_item_type: str,
    title: str,
    description: Optional[str] = None,
    additional_fields: Optional[Dict[str, Any]] = None
) -> Dict[str, Any]:
    """Create a new work item in Azure DevOps.
    
    Use this tool to create work items such as Bug, Task, User Story, Feature, or Epic
    on an Azure DevOps board. The work item type must match one defined in your project's
    process template.
    
    Args:
        work_item_type: The type of work item (e.g., "Bug", "Task", "User Story", "Feature", "Epic").
        title: The title of the work item (required).
        description: Optional description/details for the work item.
        additional_fields: Optional dictionary of additional field name-value pairs
                          (e.g., {"System.State": "Active", "System.Priority": "2"}).
    
    Returns:
        On success: {"status": "success", "result": {"id": <work_item_id>, "url": <url>, 
                     "fields": <all_fields>}}
        On error: {"status": "error", "error_message": <description>}
    """
    try:
        config = _get_ado_config()
        
        url = f"{config['base_url']}workitems/${work_item_type}?api-version=7.1"
        headers = {
            "Content-Type": "application/json-patch+json",
            "Authorization": f"Basic {config['auth_header']}"
        }
        
        # Build JSON Patch document
        json_patch_document = [
            {
                "op": "add",
                "path": "/fields/System.Title",
                "from": None,
                "value": title
            }
        ]
        
        if description:
            json_patch_document.append({
                "op": "add",
                "path": "/fields/System.Description",
                "from": None,
                "value": description
            })
        
        # Add any additional fields
        if additional_fields:
            for field_name, field_value in additional_fields.items():
                json_patch_document.append({
                    "op": "add",
                    "path": f"/fields/{field_name}",
                    "from": None,
                    "value": field_value
                })
        
        response = requests.post(url, headers=headers, data=json.dumps(json_patch_document))
        response.raise_for_status()
        
        work_item = response.json()
        
        return {
            "status": "success",
            "result": {
                "id": work_item['id'],
                "url": work_item.get('url', ''),
                "fields": work_item.get('fields', {})
            }
        }
        
    except ValueError as ve:
        return {"status": "error", "error_message": str(ve)}
    except requests.exceptions.HTTPError as he:
        error_detail = f"HTTP {he.response.status_code}: {he.response.text}"
        return {"status": "error", "error_message": error_detail}
    except requests.exceptions.RequestException as re:
        return {"status": "error", "error_message": f"Request failed: {str(re)}"}
    except Exception as e:
        return {"status": "error", "error_message": f"Unexpected error: {str(e)}"}


def get_ado_work_item(work_item_id: int) -> Dict[str, Any]:
    """Retrieve a specific work item by its ID.
    
    Use this tool to get detailed information about a work item, including all its fields
    (title, state, assigned to, description, etc.).
    
    Args:
        work_item_id: The ID of the work item to retrieve.
    
    Returns:
        On success: {"status": "success", "result": {"id": <id>, "rev": <revision>, 
                     "fields": <all_fields>, "url": <url>}}
        On error: {"status": "error", "error_message": <description>}
    """
    try:
        config = _get_ado_config()
        
        url = f"{config['base_url']}workitems/{work_item_id}?api-version=7.1"
        headers = {
            "Accept": "application/json",
            "Authorization": f"Basic {config['auth_header']}"
        }
        
        response = requests.get(url, headers=headers)
        response.raise_for_status()
        
        work_item = response.json()
        
        return {
            "status": "success",
            "result": {
                "id": work_item['id'],
                "rev": work_item.get('rev'),
                "fields": work_item.get('fields', {}),
                "url": work_item.get('url', '')
            }
        }
        
    except ValueError as ve:
        return {"status": "error", "error_message": str(ve)}
    except requests.exceptions.HTTPError as he:
        if he.response.status_code == 404:
            return {"status": "error", "error_message": f"Work item {work_item_id} not found"}
        error_detail = f"HTTP {he.response.status_code}: {he.response.text}"
        return {"status": "error", "error_message": error_detail}
    except requests.exceptions.RequestException as re:
        return {"status": "error", "error_message": f"Request failed: {str(re)}"}
    except Exception as e:
        return {"status": "error", "error_message": f"Unexpected error: {str(e)}"}


def update_ado_work_item(
    work_item_id: int,
    field_updates: Dict[str, Any]
) -> Dict[str, Any]:
    """Update one or more fields of an existing work item.
    
    Use this tool to modify work item fields such as state, priority, assigned to,
    description, or any custom fields. Multiple fields can be updated in a single call.
    
    Args:
        work_item_id: The ID of the work item to update.
        field_updates: Dictionary mapping field names to new values. 
                      Common fields include:
                      - "System.State" (e.g., "Active", "Resolved", "Closed")
                      - "System.AssignedTo" (user email or display name)
                      - "System.Priority" (e.g., "1", "2", "3")
                      - "System.Description" (HTML or plain text)
                      - "System.Tags" (semicolon-separated tags)
    
    Returns:
        On success: {"status": "success", "result": {"id": <id>, "rev": <new_revision>, 
                     "fields": <updated_fields>}}
        On error: {"status": "error", "error_message": <description>}
    """
    try:
        config = _get_ado_config()
        
        if not field_updates:
            return {"status": "error", "error_message": "field_updates cannot be empty"}
        
        url = f"{config['base_url']}workitems/{work_item_id}?api-version=7.1"
        headers = {
            "Content-Type": "application/json-patch+json",
            "Authorization": f"Basic {config['auth_header']}"
        }
        
        # Build JSON Patch document with replace operations
        json_patch_document = []
        for field_name, field_value in field_updates.items():
            json_patch_document.append({
                "op": "replace",
                "path": f"/fields/{field_name}",
                "value": field_value
            })
        
        response = requests.patch(url, headers=headers, data=json.dumps(json_patch_document))
        response.raise_for_status()
        
        work_item = response.json()
        
        return {
            "status": "success",
            "result": {
                "id": work_item['id'],
                "rev": work_item.get('rev'),
                "fields": work_item.get('fields', {}),
                "url": work_item.get('url', '')
            }
        }
        
    except ValueError as ve:
        return {"status": "error", "error_message": str(ve)}
    except requests.exceptions.HTTPError as he:
        if he.response.status_code == 404:
            return {"status": "error", "error_message": f"Work item {work_item_id} not found"}
        error_detail = f"HTTP {he.response.status_code}: {he.response.text}"
        return {"status": "error", "error_message": error_detail}
    except requests.exceptions.RequestException as re:
        return {"status": "error", "error_message": f"Request failed: {str(re)}"}
    except Exception as e:
        return {"status": "error", "error_message": f"Unexpected error: {str(e)}"}


def list_ado_work_items(work_item_ids: List[int]) -> Dict[str, Any]:
    """Retrieve multiple work items by their IDs in a batch operation.
    
    Use this tool to efficiently fetch details for multiple work items at once.
    Maximum 200 work item IDs per request.
    
    Args:
        work_item_ids: List of work item IDs to retrieve (max 200).
    
    Returns:
        On success: {"status": "success", "result": {"count": <number>, 
                     "work_items": [<work_item_1>, <work_item_2>, ...]}}
        On error: {"status": "error", "error_message": <description>}
    """
    try:
        config = _get_ado_config()
        
        if not work_item_ids:
            return {"status": "error", "error_message": "work_item_ids cannot be empty"}
        
        if len(work_item_ids) > 200:
            return {
                "status": "error",
                "error_message": "Maximum 200 work item IDs allowed per request. "
                                f"Received {len(work_item_ids)} IDs."
            }
        
        url = f"{config['base_url']}workitemsbatch?api-version=7.1"
        headers = {
            "Content-Type": "application/json",
            "Accept": "application/json",
            "Authorization": f"Basic {config['auth_header']}"
        }
        
        request_body = {
            "ids": work_item_ids,
            "$expand": "fields"
        }
        
        response = requests.post(url, headers=headers, data=json.dumps(request_body))
        response.raise_for_status()
        
        result = response.json()
        work_items = result.get('value', [])
        
        return {
            "status": "success",
            "result": {
                "count": len(work_items),
                "work_items": [
                    {
                        "id": item['id'],
                        "rev": item.get('rev'),
                        "fields": item.get('fields', {}),
                        "url": item.get('url', '')
                    }
                    for item in work_items
                ]
            }
        }
        
    except ValueError as ve:
        return {"status": "error", "error_message": str(ve)}
    except requests.exceptions.HTTPError as he:
        error_detail = f"HTTP {he.response.status_code}: {he.response.text}"
        return {"status": "error", "error_message": error_detail}
    except requests.exceptions.RequestException as re:
        return {"status": "error", "error_message": f"Request failed: {str(re)}"}
    except Exception as e:
        return {"status": "error", "error_message": f"Unexpected error: {str(e)}"}
