# Generated by NeuroStack
# Artifact: tool/analyze_it_investment.py

"""IT Investment Planning Analyzer

Evaluates IT investment proposals using financial analysis and prioritization scoring.
Calculates ROI, NPV, payback period, and generates prioritized recommendations based on
financial metrics, strategic alignment, risk, and urgency.

Use this tool when you need to:
- Analyze the financial viability of IT investment proposals
- Compare and prioritize multiple IT initiatives
- Generate structured investment recommendations
- Calculate standard financial metrics (ROI, NPV, payback period)
"""

import math
from typing import Dict, List, Any


async def analyze_it_investment(
    project_name: str,
    initial_cost: float,
    annual_benefits: float,
    project_duration_years: int,
    discount_rate: float = 0.10,
    strategic_alignment_score: int = 5,
    implementation_risk: str = "medium",
    urgency: str = "medium",
    category: str = "infrastructure"
) -> Dict[str, Any]:
    """Analyze an IT investment proposal and generate prioritized recommendations.
    
    Args:
        project_name: Name or identifier of the IT investment project
        initial_cost: Upfront investment required (in dollars)
        annual_benefits: Expected annual financial benefits (in dollars)
        project_duration_years: Expected lifespan of benefits (years)
        discount_rate: Discount rate for NPV calculation (default 0.10 = 10%)
        strategic_alignment_score: How well project aligns with strategy (1-10 scale)
        implementation_risk: Risk level - "low", "medium", or "high"
        urgency: Business urgency - "low", "medium", "high", or "critical"
        category: Investment category - "infrastructure", "security", "productivity", 
                 "innovation", or "compliance"
    
    Returns:
        Dictionary with status and result containing:
        - financial_metrics: ROI, NPV, payback period, benefit-cost ratio
        - priority_score: Composite score (0-100)
        - recommendation: Investment priority level
        - rationale: Explanation of the recommendation
        - risk_factors: List of identified risks
        - next_steps: Suggested actions
        
        Returns error status for invalid inputs.
    """
    
    # Input validation
    try:
        # Validate numeric inputs
        if initial_cost <= 0:
            return {
                "status": "error",
                "error_message": "initial_cost must be greater than 0"
            }
        
        if annual_benefits < 0:
            return {
                "status": "error",
                "error_message": "annual_benefits cannot be negative"
            }
        
        if project_duration_years <= 0:
            return {
                "status": "error",
                "error_message": "project_duration_years must be greater than 0"
            }
        
        if discount_rate < 0:
            return {
                "status": "error",
                "error_message": "discount_rate cannot be negative"
            }
        
        if not (1 <= strategic_alignment_score <= 10):
            return {
                "status": "error",
                "error_message": "strategic_alignment_score must be between 1 and 10"
            }
        
        # Validate categorical inputs
        valid_risks = ["low", "medium", "high"]
        if implementation_risk.lower() not in valid_risks:
            return {
                "status": "error",
                "error_message": f"implementation_risk must be one of: {', '.join(valid_risks)}"
            }
        implementation_risk = implementation_risk.lower()
        
        valid_urgencies = ["low", "medium", "high", "critical"]
        if urgency.lower() not in valid_urgencies:
            return {
                "status": "error",
                "error_message": f"urgency must be one of: {', '.join(valid_urgencies)}"
            }
        urgency = urgency.lower()
        
        valid_categories = ["infrastructure", "security", "productivity", "innovation", "compliance"]
        if category.lower() not in valid_categories:
            return {
                "status": "error",
                "error_message": f"category must be one of: {', '.join(valid_categories)}"
            }
        category = category.lower()
        
    except (TypeError, ValueError) as e:
        return {
            "status": "error",
            "error_message": f"Invalid input type: {str(e)}"
        }
    
    # Calculate financial metrics
    total_benefits = annual_benefits * project_duration_years
    
    # ROI Percentage
    roi_percentage = ((total_benefits - initial_cost) / initial_cost) * 100
    
    # Net Present Value (NPV)
    npv = -initial_cost
    for year in range(1, project_duration_years + 1):
        npv += annual_benefits / math.pow(1 + discount_rate, year)
    
    # Payback Period (in years)
    if annual_benefits > 0:
        payback_period_years = initial_cost / annual_benefits
    else:
        payback_period_years = float('inf')
    
    # Benefit-Cost Ratio
    if initial_cost > 0:
        benefit_cost_ratio = total_benefits / initial_cost
    else:
        benefit_cost_ratio = 0
    
    # Calculate priority score (0-100 scale)
    # Weighting: 40% financial, 30% strategic, 20% risk, 10% urgency
    
    # Financial score (0-40 points)
    financial_score = 0
    if roi_percentage > 100:
        financial_score = 40
    elif roi_percentage > 50:
        financial_score = 35
    elif roi_percentage > 25:
        financial_score = 30
    elif roi_percentage > 0:
        financial_score = 20
    elif roi_percentage > -25:
        financial_score = 10
    else:
        financial_score = 0
    
    # NPV bonus (additional points if NPV is strongly positive)
    if npv > initial_cost:
        financial_score = min(40, financial_score + 5)
    
    # Strategic alignment score (0-30 points)
    strategic_score = (strategic_alignment_score / 10) * 30
    
    # Risk score (0-20 points, lower risk = higher score)
    risk_scores = {"low": 20, "medium": 12, "high": 5}
    risk_score = risk_scores[implementation_risk]
    
    # Urgency score (0-10 points)
    urgency_scores = {"low": 3, "medium": 6, "high": 9, "critical": 10}
    urgency_score = urgency_scores[urgency]
    
    # Calculate total priority score
    priority_score = financial_score + strategic_score + risk_score + urgency_score
    priority_score = round(priority_score, 1)
    
    # Generate recommendation
    if priority_score >= 75:
        recommendation = "high_priority"
        recommendation_text = "High Priority - Recommend immediate approval and funding"
    elif priority_score >= 55:
        recommendation = "medium_priority"
        recommendation_text = "Medium Priority - Recommend approval pending budget availability"
    elif priority_score >= 35:
        recommendation = "low_priority"
        recommendation_text = "Low Priority - Consider for future investment cycles"
    else:
        recommendation = "defer"
        recommendation_text = "Defer - Does not meet investment criteria at this time"
    
    # Build rationale
    rationale_parts = []
    
    if roi_percentage > 50:
        rationale_parts.append(f"Strong ROI of {roi_percentage:.1f}%")
    elif roi_percentage > 0:
        rationale_parts.append(f"Positive ROI of {roi_percentage:.1f}%")
    else:
        rationale_parts.append(f"Negative ROI of {roi_percentage:.1f}%")
    
    if npv > 0:
        rationale_parts.append(f"positive NPV of ${npv:,.0f}")
    else:
        rationale_parts.append(f"negative NPV of ${npv:,.0f}")
    
    if payback_period_years < 2:
        rationale_parts.append("quick payback period")
    elif payback_period_years < 5:
        rationale_parts.append("reasonable payback period")
    elif payback_period_years != float('inf'):
        rationale_parts.append("extended payback period")
    
    if strategic_alignment_score >= 8:
        rationale_parts.append("high strategic alignment")
    elif strategic_alignment_score >= 5:
        rationale_parts.append("moderate strategic alignment")
    else:
        rationale_parts.append("limited strategic alignment")
    
    rationale = f"{recommendation_text}. {', '.join(rationale_parts).capitalize()}."
    
    # Identify risk factors
    risk_factors = []
    
    if implementation_risk == "high":
        risk_factors.append("High implementation risk - may face technical or organizational challenges")
    elif implementation_risk == "medium":
        risk_factors.append("Medium implementation risk - requires careful project management")
    
    if payback_period_years > 5 and payback_period_years != float('inf'):
        risk_factors.append(f"Long payback period of {payback_period_years:.1f} years")
    elif payback_period_years == float('inf'):
        risk_factors.append("No clear payback period - benefits may not cover costs")
    
    if roi_percentage < 0:
        risk_factors.append("Negative ROI indicates costs exceed benefits")
    
    if npv < 0:
        risk_factors.append("Negative NPV suggests investment destroys value at current discount rate")
    
    if annual_benefits == 0:
        risk_factors.append("Zero annual benefits - value may be non-financial")
    
    if not risk_factors:
        risk_factors.append("No major risk factors identified")
    
    # Generate next steps
    next_steps = []
    
    if recommendation in ["high_priority", "medium_priority"]:
        next_steps.append("Prepare detailed business case with implementation plan")
        next_steps.append("Identify project sponsor and assemble project team")
        next_steps.append("Develop risk mitigation strategies")
        if category == "security":
            next_steps.append("Conduct security assessment and compliance review")
        elif category == "compliance":
            next_steps.append("Validate regulatory requirements and deadlines")
        next_steps.append("Establish success metrics and KPIs")
        next_steps.append("Schedule stakeholder review and approval meetings")
    elif recommendation == "low_priority":
        next_steps.append("Add to backlog for future consideration")
        next_steps.append("Re-evaluate in next budget cycle")
        next_steps.append("Identify ways to improve ROI or reduce costs")
        next_steps.append("Consider phased or scaled-down approach")
    else:  # defer
        next_steps.append("Do not proceed with investment at this time")
        next_steps.append("Re-examine business case and benefit assumptions")
        next_steps.append("Consider alternative solutions with better ROI")
        next_steps.append("Revisit if business conditions or requirements change")
    
    # Build result
    result = {
        "project_name": project_name,
        "category": category,
        "financial_metrics": {
            "roi_percentage": round(roi_percentage, 2),
            "npv": round(npv, 2),
            "payback_period_years": round(payback_period_years, 2) if payback_period_years != float('inf') else None,
            "benefit_cost_ratio": round(benefit_cost_ratio, 2),
            "total_benefits": round(total_benefits, 2),
            "net_benefit": round(total_benefits - initial_cost, 2)
        },
        "priority_score": priority_score,
        "priority_breakdown": {
            "financial_score": round(financial_score, 1),
            "strategic_score": round(strategic_score, 1),
            "risk_score": round(risk_score, 1),
            "urgency_score": round(urgency_score, 1)
        },
        "recommendation": recommendation,
        "rationale": rationale,
        "risk_factors": risk_factors,
        "next_steps": next_steps
    }
    
    return {
        "status": "success",
        "result": result
    }
