# Generated by NeuroStack
# Artifact: tool/analyze_codebase_risks.py

"""
Codebase risk management tool for static analysis of Python code.

Analyzes Python code files for security vulnerabilities, quality issues,
complexity metrics, and maintainability risks. Returns a comprehensive
risk report with severity-based findings and actionable recommendations.
"""

import ast
import re
from pathlib import Path
from typing import Optional, List, Dict, Any


async def analyze_codebase_risks(
    file_path: Optional[str] = None,
    code_content: Optional[str] = None,
    check_categories: Optional[List[str]] = None,
    severity_threshold: str = "low"
) -> Dict[str, Any]:
    """
    Analyze Python code for security vulnerabilities, quality issues, and risks.
    
    Use this tool when you need to assess code for potential security issues,
    maintainability concerns, or code quality problems. Provides static analysis
    with severity-based findings and recommendations.
    
    Args:
        file_path: Path to a Python file to analyze. Either this or code_content
            must be provided, but not both.
        code_content: Direct Python code string to analyze. Either this or
            file_path must be provided, but not both.
        check_categories: List of check categories to run. Valid options:
            ["security", "quality", "complexity", "dependencies", "documentation"].
            If None, all categories are checked.
        severity_threshold: Minimum severity level to report. Valid options:
            "low", "medium", "high", "critical". Defaults to "low".
    
    Returns:
        Success: {
            "status": "success",
            "result": {
                "summary": {
                    "total_issues": int,
                    "critical": int,
                    "high": int,
                    "medium": int,
                    "low": int,
                    "risk_score": float (0-100)
                },
                "findings": [
                    {
                        "category": str,
                        "severity": str,
                        "line_number": int,
                        "issue": str,
                        "description": str,
                        "recommendation": str,
                        "code_snippet": str
                    }
                ],
                "metrics": {
                    "lines_of_code": int,
                    "complexity_score": float,
                    "maintainability_index": float
                }
            }
        }
        Error: {"status": "error", "error_message": str}
    """
    try:
        # Validate inputs
        if file_path is None and code_content is None:
            return {
                "status": "error",
                "error_message": "Either file_path or code_content must be provided"
            }
        
        if file_path is not None and code_content is not None:
            return {
                "status": "error",
                "error_message": "Provide only one of file_path or code_content, not both"
            }
        
        # Validate severity threshold
        valid_severities = ["low", "medium", "high", "critical"]
        if severity_threshold not in valid_severities:
            return {
                "status": "error",
                "error_message": f"Invalid severity_threshold. Must be one of: {', '.join(valid_severities)}"
            }
        
        # Read code from file if path provided
        if file_path:
            try:
                path = Path(file_path)
                
                # Security: validate path to prevent directory traversal
                if ".." in str(path) or str(path).startswith("/"):
                    return {
                        "status": "error",
                        "error_message": "Invalid file path: directory traversal not allowed"
                    }
                
                if not path.exists():
                    return {
                        "status": "error",
                        "error_message": f"File not found: {file_path}"
                    }
                
                if not path.is_file():
                    return {
                        "status": "error",
                        "error_message": f"Path is not a file: {file_path}"
                    }
                
                code_content = path.read_text(encoding="utf-8")
            except PermissionError:
                return {
                    "status": "error",
                    "error_message": f"Permission denied reading file: {file_path}"
                }
            except Exception as e:
                return {
                    "status": "error",
                    "error_message": f"Error reading file: {str(e)}"
                }
        
        # Set default check categories if not provided
        if check_categories is None:
            check_categories = ["security", "quality", "complexity", "dependencies", "documentation"]
        
        # Validate check categories
        valid_categories = ["security", "quality", "complexity", "dependencies", "documentation"]
        for category in check_categories:
            if category not in valid_categories:
                return {
                    "status": "error",
                    "error_message": f"Invalid category '{category}'. Valid categories: {', '.join(valid_categories)}"
                }
        
        # Parse code into AST
        try:
            tree = ast.parse(code_content)
        except SyntaxError as e:
            return {
                "status": "error",
                "error_message": f"Syntax error in Python code at line {e.lineno}: {e.msg}"
            }
        
        # Initialize findings
        findings = []
        
        # Run analyses
        if "security" in check_categories:
            findings.extend(_check_security(tree, code_content))
        
        if "quality" in check_categories:
            findings.extend(_check_quality(tree, code_content))
        
        if "complexity" in check_categories:
            findings.extend(_check_complexity(tree, code_content))
        
        if "dependencies" in check_categories:
            findings.extend(_check_dependencies(tree))
        
        if "documentation" in check_categories:
            findings.extend(_check_documentation(tree, code_content))
        
        # Filter by severity threshold
        severity_order = {"low": 0, "medium": 1, "high": 2, "critical": 3}
        threshold_level = severity_order[severity_threshold]
        filtered_findings = [
            f for f in findings 
            if severity_order.get(f["severity"], 0) >= threshold_level
        ]
        
        # Calculate summary
        summary = {
            "total_issues": len(filtered_findings),
            "critical": sum(1 for f in filtered_findings if f["severity"] == "critical"),
            "high": sum(1 for f in filtered_findings if f["severity"] == "high"),
            "medium": sum(1 for f in filtered_findings if f["severity"] == "medium"),
            "low": sum(1 for f in filtered_findings if f["severity"] == "low"),
            "risk_score": _calculate_risk_score(filtered_findings)
        }
        
        # Calculate metrics
        metrics = _calculate_metrics(tree, code_content)
        
        return {
            "status": "success",
            "result": {
                "summary": summary,
                "findings": filtered_findings,
                "metrics": metrics
            }
        }
        
    except Exception as e:
        return {
            "status": "error",
            "error_message": f"Unexpected error during analysis: {str(e)}"
        }


def _check_security(tree: ast.AST, code_content: str) -> List[Dict[str, Any]]:
    """Check for security vulnerabilities."""
    findings = []
    lines = code_content.split('\n')
    
    class SecurityVisitor(ast.NodeVisitor):
        def visit_Call(self, node):
            # Check for dangerous functions
            if isinstance(node.func, ast.Name):
                if node.func.id in ['eval', 'exec']:
                    findings.append({
                        "category": "security",
                        "severity": "critical",
                        "line_number": node.lineno,
                        "issue": f"Dangerous function: {node.func.id}",
                        "description": f"Use of {node.func.id}() can execute arbitrary code and is a critical security risk",
                        "recommendation": f"Avoid using {node.func.id}(). Consider safer alternatives like ast.literal_eval() for data parsing",
                        "code_snippet": _get_code_snippet(lines, node.lineno)
                    })
                elif node.func.id == 'compile':
                    findings.append({
                        "category": "security",
                        "severity": "high",
                        "line_number": node.lineno,
                        "issue": "Dynamic code compilation",
                        "description": "compile() can create code objects from strings, posing security risks",
                        "recommendation": "Avoid dynamic code compilation. Use static code or configuration-driven approaches",
                        "code_snippet": _get_code_snippet(lines, node.lineno)
                    })
            
            # Check for pickle usage
            if isinstance(node.func, ast.Attribute):
                if node.func.attr in ['loads', 'load'] and isinstance(node.func.value, ast.Name):
                    if node.func.value.id == 'pickle':
                        findings.append({
                            "category": "security",
                            "severity": "high",
                            "line_number": node.lineno,
                            "issue": "Unsafe deserialization with pickle",
                            "description": "pickle.loads/load can execute arbitrary code during deserialization",
                            "recommendation": "Use safer serialization formats like JSON or validate pickle data source",
                            "code_snippet": _get_code_snippet(lines, node.lineno)
                        })
            
            self.generic_visit(node)
        
        def visit_Import(self, node):
            # Check for weak crypto libraries
            for alias in node.names:
                if alias.name in ['md5', 'sha1']:
                    findings.append({
                        "category": "security",
                        "severity": "medium",
                        "line_number": node.lineno,
                        "issue": f"Weak cryptographic algorithm: {alias.name}",
                        "description": f"{alias.name.upper()} is cryptographically broken and should not be used for security",
                        "recommendation": "Use SHA-256 or stronger algorithms from hashlib",
                        "code_snippet": _get_code_snippet(lines, node.lineno)
                    })
            self.generic_visit(node)
    
    # Check for hardcoded secrets using regex
    secret_patterns = [
        (r'password\s*=\s*["\'][^"\']+["\']', "Possible hardcoded password"),
        (r'api[_-]?key\s*=\s*["\'][^"\']+["\']', "Possible hardcoded API key"),
        (r'secret\s*=\s*["\'][^"\']+["\']', "Possible hardcoded secret"),
        (r'token\s*=\s*["\'][^"\']+["\']', "Possible hardcoded token"),
    ]
    
    for i, line in enumerate(lines, 1):
        for pattern, issue in secret_patterns:
            if re.search(pattern, line, re.IGNORECASE):
                findings.append({
                    "category": "security",
                    "severity": "critical",
                    "line_number": i,
                    "issue": issue,
                    "description": "Hardcoded credentials in source code pose a security risk",
                    "recommendation": "Use environment variables or secure credential management systems",
                    "code_snippet": line.strip()
                })
    
    # Check for SQL injection patterns
    for i, line in enumerate(lines, 1):
        if re.search(r'(execute|cursor)\s*\([^)]*["\'].*%s.*["\'].*%', line):
            findings.append({
                "category": "security",
                "severity": "high",
                "line_number": i,
                "issue": "Potential SQL injection vulnerability",
                "description": "String formatting in SQL queries can lead to SQL injection",
                "recommendation": "Use parameterized queries with proper placeholders",
                "code_snippet": line.strip()
            })
    
    visitor = SecurityVisitor()
    visitor.visit(tree)
    
    return findings


def _check_quality(tree: ast.AST, code_content: str) -> List[Dict[str, Any]]:
    """Check for code quality issues."""
    findings = []
    lines = code_content.split('\n')
    
    class QualityVisitor(ast.NodeVisitor):
        def visit_FunctionDef(self, node):
            # Check for poor naming
            if len(node.name) <= 2 and node.name not in ['id', 'at', 'to', 'by']:
                findings.append({
                    "category": "quality",
                    "severity": "low",
                    "line_number": node.lineno,
                    "issue": "Poor function naming",
                    "description": f"Function name '{node.name}' is too short and unclear",
                    "recommendation": "Use descriptive function names that explain what the function does",
                    "code_snippet": _get_code_snippet(lines, node.lineno)
                })
            
            # Check for too many arguments
            args_count = len(node.args.args) + len(node.args.kwonlyargs)
            if args_count > 7:
                findings.append({
                    "category": "quality",
                    "severity": "medium",
                    "line_number": node.lineno,
                    "issue": f"Too many parameters ({args_count})",
                    "description": "Functions with many parameters are hard to understand and maintain",
                    "recommendation": "Consider using a configuration object or breaking the function into smaller pieces",
                    "code_snippet": _get_code_snippet(lines, node.lineno)
                })
            
            self.generic_visit(node)
        
        def visit_Name(self, node):
            # Check for deprecated names
            if node.id in ['unicode', 'basestring', 'xrange']:
                findings.append({
                    "category": "quality",
                    "severity": "medium",
                    "line_number": node.lineno,
                    "issue": f"Deprecated Python 2 name: {node.id}",
                    "description": f"'{node.id}' is a Python 2 construct not available in Python 3",
                    "recommendation": "Update to Python 3 equivalents (str, str, range)",
                    "code_snippet": _get_code_snippet(lines, node.lineno)
                })
            self.generic_visit(node)
        
        def visit_Try(self, node):
            # Check for bare except
            for handler in node.handlers:
                if handler.type is None:
                    findings.append({
                        "category": "quality",
                        "severity": "medium",
                        "line_number": handler.lineno,
                        "issue": "Bare except clause",
                        "description": "Catching all exceptions can hide bugs and make debugging difficult",
                        "recommendation": "Catch specific exception types or at minimum use 'except Exception:'",
                        "code_snippet": _get_code_snippet(lines, handler.lineno)
                    })
            self.generic_visit(node)
    
    visitor = QualityVisitor()
    visitor.visit(tree)
    
    return findings


def _check_complexity(tree: ast.AST, code_content: str) -> List[Dict[str, Any]]:
    """Check for complexity issues."""
    findings = []
    lines = code_content.split('\n')
    
    class ComplexityVisitor(ast.NodeVisitor):
        def visit_FunctionDef(self, node):
            # Calculate cyclomatic complexity
            complexity = _calculate_cyclomatic_complexity(node)
            
            if complexity > 10:
                severity = "high" if complexity > 20 else "medium"
                findings.append({
                    "category": "complexity",
                    "severity": severity,
                    "line_number": node.lineno,
                    "issue": f"High cyclomatic complexity ({complexity})",
                    "description": f"Function '{node.name}' has complexity of {complexity}, making it hard to test and maintain",
                    "recommendation": "Break function into smaller, focused functions with complexity < 10",
                    "code_snippet": _get_code_snippet(lines, node.lineno)
                })
            
            # Check function length
            if hasattr(node, 'end_lineno'):
                length = node.end_lineno - node.lineno
                if length > 50:
                    findings.append({
                        "category": "complexity",
                        "severity": "medium",
                        "line_number": node.lineno,
                        "issue": f"Long function ({length} lines)",
                        "description": f"Function '{node.name}' is {length} lines long",
                        "recommendation": "Break long functions into smaller, focused functions (aim for < 50 lines)",
                        "code_snippet": _get_code_snippet(lines, node.lineno)
                    })
            
            # Check nesting depth
            max_depth = _calculate_max_nesting(node)
            if max_depth > 4:
                findings.append({
                    "category": "complexity",
                    "severity": "medium",
                    "line_number": node.lineno,
                    "issue": f"Deep nesting (depth {max_depth})",
                    "description": f"Function '{node.name}' has nesting depth of {max_depth}",
                    "recommendation": "Reduce nesting by extracting logic into separate functions or using early returns",
                    "code_snippet": _get_code_snippet(lines, node.lineno)
                })
            
            self.generic_visit(node)
    
    visitor = ComplexityVisitor()
    visitor.visit(tree)
    
    return findings


def _check_dependencies(tree: ast.AST) -> List[Dict[str, Any]]:
    """Check dependency-related issues."""
    findings = []
    
    class DependencyVisitor(ast.NodeVisitor):
        def __init__(self):
            self.imports = []
        
        def visit_Import(self, node):
            for alias in node.names:
                self.imports.append((alias.name, node.lineno))
            self.generic_visit(node)
        
        def visit_ImportFrom(self, node):
            if node.module:
                self.imports.append((node.module, node.lineno))
            self.generic_visit(node)
    
    visitor = DependencyVisitor()
    visitor.visit(tree)
    
    # Check for wildcard imports
    class WildcardVisitor(ast.NodeVisitor):
        def visit_ImportFrom(self, node):
            for alias in node.names:
                if alias.name == '*':
                    findings.append({
                        "category": "dependencies",
                        "severity": "medium",
                        "line_number": node.lineno,
                        "issue": "Wildcard import",
                        "description": f"Wildcard import from {node.module or '?'} pollutes namespace",
                        "recommendation": "Import specific names or use qualified imports",
                        "code_snippet": f"from {node.module} import *"
                    })
            self.generic_visit(node)
    
    wildcard_visitor = WildcardVisitor()
    wildcard_visitor.visit(tree)
    
    return findings


def _check_documentation(tree: ast.AST, code_content: str) -> List[Dict[str, Any]]:
    """Check documentation quality."""
    findings = []
    lines = code_content.split('\n')
    
    class DocVisitor(ast.NodeVisitor):
        def visit_FunctionDef(self, node):
            # Check for missing docstrings
            docstring = ast.get_docstring(node)
            if not docstring and not node.name.startswith('_'):
                findings.append({
                    "category": "documentation",
                    "severity": "low",
                    "line_number": node.lineno,
                    "issue": "Missing docstring",
                    "description": f"Public function '{node.name}' has no docstring",
                    "recommendation": "Add a docstring describing the function's purpose, args, and return value",
                    "code_snippet": _get_code_snippet(lines, node.lineno)
                })
            self.generic_visit(node)
        
        def visit_ClassDef(self, node):
            # Check for missing class docstrings
            docstring = ast.get_docstring(node)
            if not docstring and not node.name.startswith('_'):
                findings.append({
                    "category": "documentation",
                    "severity": "low",
                    "line_number": node.lineno,
                    "issue": "Missing class docstring",
                    "description": f"Public class '{node.name}' has no docstring",
                    "recommendation": "Add a docstring describing the class purpose and usage",
                    "code_snippet": _get_code_snippet(lines, node.lineno)
                })
            self.generic_visit(node)
    
    visitor = DocVisitor()
    visitor.visit(tree)
    
    # Check for TODO/FIXME markers
    for i, line in enumerate(lines, 1):
        if re.search(r'\b(TODO|FIXME|XXX|HACK)\b', line, re.IGNORECASE):
            findings.append({
                "category": "documentation",
                "severity": "low",
                "line_number": i,
                "issue": "Technical debt marker",
                "description": "Code contains TODO/FIXME marker indicating incomplete work",
                "recommendation": "Address the marked issue or create a tracking ticket",
                "code_snippet": line.strip()
            })
    
    return findings


def _calculate_cyclomatic_complexity(node: ast.FunctionDef) -> int:
    """Calculate cyclomatic complexity of a function."""
    complexity = 1  # Base complexity
    
    class ComplexityCounter(ast.NodeVisitor):
        def __init__(self):
            self.complexity = 0
        
        def visit_If(self, node):
            self.complexity += 1
            self.generic_visit(node)
        
        def visit_While(self, node):
            self.complexity += 1
            self.generic_visit(node)
        
        def visit_For(self, node):
            self.complexity += 1
            self.generic_visit(node)
        
        def visit_ExceptHandler(self, node):
            self.complexity += 1
            self.generic_visit(node)
        
        def visit_With(self, node):
            self.complexity += 1
            self.generic_visit(node)
        
        def visit_BoolOp(self, node):
            self.complexity += len(node.values) - 1
            self.generic_visit(node)
    
    counter = ComplexityCounter()
    counter.visit(node)
    
    return complexity + counter.complexity


def _calculate_max_nesting(node: ast.FunctionDef) -> int:
    """Calculate maximum nesting depth in a function."""
    
    class NestingCounter(ast.NodeVisitor):
        def __init__(self):
            self.max_depth = 0
            self.current_depth = 0
        
        def _visit_nested(self, node):
            self.current_depth += 1
            self.max_depth = max(self.max_depth, self.current_depth)
            self.generic_visit(node)
            self.current_depth -= 1
        
        def visit_If(self, node):
            self._visit_nested(node)
        
        def visit_While(self, node):
            self._visit_nested(node)
        
        def visit_For(self, node):
            self._visit_nested(node)
        
        def visit_With(self, node):
            self._visit_nested(node)
        
        def visit_Try(self, node):
            self._visit_nested(node)
    
    counter = NestingCounter()
    counter.visit(node)
    
    return counter.max_depth


def _calculate_risk_score(findings: List[Dict[str, Any]]) -> float:
    """Calculate overall risk score from findings (0-100)."""
    if not findings:
        return 0.0
    
    severity_weights = {
        "critical": 10.0,
        "high": 5.0,
        "medium": 2.0,
        "low": 0.5
    }
    
    total_weight = sum(severity_weights.get(f["severity"], 0) for f in findings)
    
    # Normalize to 0-100 scale (cap at 100)
    risk_score = min(total_weight * 2, 100.0)
    
    return round(risk_score, 2)


def _calculate_metrics(tree: ast.AST, code_content: str) -> Dict[str, Any]:
    """Calculate code metrics."""
    lines = code_content.split('\n')
    
    # Count non-empty, non-comment lines
    loc = sum(1 for line in lines if line.strip() and not line.strip().startswith('#'))
    
    # Calculate average complexity
    class ComplexityCollector(ast.NodeVisitor):
        def __init__(self):
            self.complexities = []
        
        def visit_FunctionDef(self, node):
            self.complexities.append(_calculate_cyclomatic_complexity(node))
            self.generic_visit(node)
    
    collector = ComplexityCollector()
    collector.visit(tree)
    
    avg_complexity = sum(collector.complexities) / len(collector.complexities) if collector.complexities else 0
    
    # Simple maintainability index approximation
    # Based on lines of code and complexity
    maintainability = max(0, 100 - (avg_complexity * 2) - (loc / 10))
    
    return {
        "lines_of_code": loc,
        "complexity_score": round(avg_complexity, 2),
        "maintainability_index": round(maintainability, 2)
    }


def _get_code_snippet(lines: List[str], line_number: int, context: int = 0) -> str:
    """Get a code snippet around the given line number."""
    if not lines or line_number < 1 or line_number > len(lines):
        return ""
    
    # Adjust for 0-based indexing
    idx = line_number - 1
    
    start = max(0, idx - context)
    end = min(len(lines), idx + context + 1)
    
    snippet_lines = lines[start:end]
    return '\n'.join(line.rstrip() for line in snippet_lines).strip()
