# Generated by NeuroStack
# Vendored from platform origin: tool/classify_ticket_tools (upstream_version=platform)

"""
Generated Tools - classify_ticket_tools.py

Auto-generated tools created by the Tool Generator.
Generated on: 2024-10-27 23:07:00
Total tools: 1
Category: Ticket Classification
"""

from typing import Dict, Any


def classify_ticket(text: str) -> Dict[str, Any]:
    """
    Classifies a support ticket into a category based on keyword matching.

    Args:
        text (str): The ticket summary and description combined.

    Returns:
        Dict[str, Any]: A dictionary containing the classification results, including category,
                         urgency score, and confidence level.
                         Example: {"success": True, "message": "Ticket classified",
                                   "data": {"category": "billing", "urgency_score": 3, "confidence": 0.75}}
    """
    try:
        text = text.lower()

        # Define keywords for each category
        billing_keywords = ["invoice", "charge", "payment", "refund", "subscription", "price", "cost"]
        account_access_keywords = ["login", "password", "locked", "cant access", "authentication", "credentials", "sign in", "2fa"]
        known_bug_keywords = ["error", "bug", "broken", "not working", "crash", "fails", "exception"]
        how_to_keywords = ["how do i", "how to", "where is", "can i", "steps to", "guide", "tutorial"]
        escalation_keywords = ["urgent", "critical", "lawsuit", "legal", "unacceptable", "furious", "immediately", "escalate", "manager"]

        # Define urgency keywords and scores
        urgency_5_keywords = ["critical", "urgent", "emergency", "production down", "legal", "lawsuit"]
        urgency_4_keywords = ["broken", "not working", "blocked", "asap"]
        urgency_3_keywords = ["error", "failing", "issue", "problem"]
        urgency_2_keywords = ["slow", "confusing", "unclear", "how do i"]

        def calculate_urgency(text: str) -> int:
            """Calculates the urgency score based on keywords."""
            if any(keyword in text for keyword in urgency_5_keywords):
                return 5
            if any(keyword in text for keyword in urgency_4_keywords):
                return 4
            if any(keyword in text for keyword in urgency_3_keywords):
                return 3
            if any(keyword in text for keyword in urgency_2_keywords):
                return 2
            return 1

        urgency_score = calculate_urgency(text)

        # Classify the ticket
        category = "other"
        confidence = 0.4
        keyword_matches = 0

        if any(keyword in text for keyword in billing_keywords):
            category = "billing"
            keyword_matches += len([keyword for keyword in billing_keywords if keyword in text])
        if any(keyword in text for keyword in account_access_keywords):
            category = "account-access"
            keyword_matches += len([keyword for keyword in account_access_keywords if keyword in text])
        if any(keyword in text for keyword in known_bug_keywords):
            category = "known-bug"
            keyword_matches += len([keyword for keyword in known_bug_keywords if keyword in text])
        if any(keyword in text for keyword in how_to_keywords):
            category = "how-to"
            keyword_matches += len([keyword for keyword in how_to_keywords if keyword in text])
        if any(keyword in text for keyword in escalation_keywords) or urgency_score == 5:
            category = "escalation"
            keyword_matches += len([keyword for keyword in escalation_keywords if keyword in text])

        if keyword_matches >= 3:
            confidence = 0.9
        elif keyword_matches == 2:
            confidence = 0.75
        elif keyword_matches == 1:
            confidence = 0.6

        return {
            "success": True,
            "message": "Ticket classified",
            "data": {
                "category": category,
                "urgency_score": urgency_score,
                "confidence": confidence
            }
        }

    except Exception as e:
        return {
            "success": False,
            "message": f"Error: {str(e)}",
            "data": {}
        }
