# Generated by NeuroStack
# Vendored from platform origin: tool/database_tools (upstream_version=platform)

"""
Generated Tools - database_tools.py

Auto-generated tools created by the Tool Generator.
Generated on: 2025-07-04 17:30:13
Total tools: 3
"""

from typing import Dict, Any, List, Optional
import os
from dotenv import load_dotenv, find_dotenv
from sqlalchemy import create_engine, text

load_dotenv(find_dotenv())

# Cached SQLAlchemy connection engines
_engines = {}

def get_engine(db_path: str = None):
    """Helper to get a PostgreSQL SQLAlchemy engine."""
    db_url = os.getenv("DATABASE_URL", "postgresql://postgres:adminpassword@localhost:5432/agent_factory")
    if db_path and (db_path.startswith("postgresql://") or db_path.startswith("postgres://")):
        db_url = db_path
    if db_url not in _engines:
        _engines[db_url] = create_engine(db_url, pool_size=5, max_overflow=10)
    return _engines[db_url]


def execute_sql_query(db_path: str, sql_query: str) -> Dict[str, Any]:
    """
    Executes an SQL query against the database.

    Args:
        db_path (str): Connection string or path for the PostgreSQL database.
        sql_query (str): SQL query to execute. WARNING: Ensure SQL injection prevention!

    Returns:
        Dict[str, Any]: A dictionary containing the success status, message, and data.
                         On success, 'success' is True, 'message' is 'Query executed successfully',
                         and 'data' is a list of tuples representing the query results.
                         On failure, 'success' is False, 'message' contains the error message.
    """
    try:
        engine = get_engine(db_path)
        with engine.begin() as conn:
            result = conn.execute(text(sql_query))
            data = None
            if result.returns_rows:
                # Convert results to list of tuples to match legacy psycopg2 structure exactly
                data = [tuple(row) for row in result]

        return {
            "success": True,
            "message": "Query executed successfully",
            "data": data
        }
    except Exception as e:
        return {
            "success": False,
            "message": f"Error: {str(e)}",
            "data": None
        }


def fetch_data_from_table(db_path: str, table_name: str) -> Dict[str, Any]:
    """
    Fetches all data from a specified table in the PostgreSQL database.

    Args:
        db_path (str): Connection string or path for the PostgreSQL database.
        table_name (str): Name of the table to fetch data from.

    Returns:
        Dict[str, Any]: A dictionary containing the success status, message, and data.
                        - success (bool): True if the operation was successful, False otherwise.
                        - message (str): A message describing the outcome of the operation.
                        - data (List[tuple]): A list of tuples representing the rows from the table,
                                              or None if an error occurred.
    """
    try:
        # Input validation to prevent SQL injection
        if not isinstance(table_name, str):
            raise ValueError("Table name must be a string.")
        if not all(c.isalnum() or c == '_' for c in table_name):
            raise ValueError("Table name must contain only alphanumeric characters or underscores.")

        engine = get_engine(db_path)
        with engine.connect() as conn:
            result = conn.execute(text(f'SELECT * FROM "{table_name}"'))
            data = [tuple(row) for row in result]

        return {
            "success": True,
            "message": f"Successfully fetched data from table '{table_name}'.",
            "data": data
        }
    except ValueError as e:
        return {
            "success": False,
            "message": f"Input validation error: {str(e)}",
            "data": None
        }
    except Exception as e:
        return {
            "success": False,
            "message": f"An unexpected error occurred: {str(e)}",
            "data": None
        }


def update_database_record(db_path: str, table_name: str, column_name: str, new_value: str, where_clause: str) -> Dict[str, Any]:
    """
    Updates a record in the database based on a WHERE clause.

    Args:
        db_path (str): Connection string or path for the PostgreSQL database.
        table_name (str): Name of the table to update.
        column_name (str): Name of the column to update.
        new_value (str): The new value for the specified column.
        where_clause (str): The WHERE clause to identify the record to update (e.g., 'id = 1'). WARNING: Ensure SQL injection prevention!

    Returns:
        Dict[str, Any]: Dictionary with 'success', 'message', and relevant data keys.
    """
    try:
        # Input validation
        if not isinstance(db_path, str):
            raise TypeError("db_path must be a string.")
        if not isinstance(table_name, str):
            raise TypeError("table_name must be a string.")
        if not isinstance(column_name, str):
            raise TypeError("column_name must be a string.")
        if not isinstance(new_value, str):
            raise TypeError("new_value must be a string.")
        if not isinstance(where_clause, str):
            raise TypeError("where_clause must be a string.")
        
        engine = get_engine(db_path)
        with engine.begin() as conn:
            # Bind parameters securely using text()
            sql_query = f'UPDATE "{table_name}" SET "{column_name}" = :new_value WHERE {where_clause}'
            result = conn.execute(text(sql_query), {"new_value": new_value})
            rows_affected = result.rowcount
        
        if rows_affected > 0:
            return {
                "success": True,
                "message": f"Successfully updated {rows_affected} record(s) in {table_name}.",
                "data": {"rows_affected": rows_affected}
            }
        else:
            return {
                "success": False,
                "message": f"No records updated in {table_name}. Check the WHERE clause.",
                "data": {"rows_affected": rows_affected}
            }
            
    except Exception as e:
        return {
            "success": False,
            "message": f"Error: {str(e)}",
            "data": None
        }