# Generated by NeuroStack
# Artifact: tool/edit_picture.py

"""Picture editing tool for common image manipulation operations.

This tool provides functionality to edit images including resize, crop, rotate,
flip, adjust brightness/contrast, convert formats, and apply filters.
"""

import os
from typing import Any, Dict, Optional
from pathlib import Path

try:
    from PIL import Image, ImageEnhance, ImageFilter
except ImportError:
    Image = None
    ImageEnhance = None
    ImageFilter = None


def edit_picture(
    image_path: str,
    output_path: str,
    operation: str,
    width: Optional[int] = None,
    height: Optional[int] = None,
    maintain_aspect_ratio: bool = True,
    left: Optional[int] = None,
    top: Optional[int] = None,
    right: Optional[int] = None,
    bottom: Optional[int] = None,
    angle: Optional[float] = None,
    expand: bool = False,
    direction: Optional[str] = None,
    factor: Optional[float] = None,
    format: Optional[str] = None,
    filter_type: Optional[str] = None,
) -> Dict[str, Any]:
    """Edit a picture with various image manipulation operations.
    
    Use this tool when you need to perform common image editing tasks such as
    resizing, cropping, rotating, flipping, adjusting brightness/contrast,
    converting formats, or applying filters to images.
    
    Args:
        image_path: Path to the input image file.
        output_path: Path where the edited image will be saved.
        operation: The editing operation to perform. Valid values:
            - "resize": Scale image to new dimensions
            - "crop": Extract a rectangular region
            - "rotate": Rotate image by specified angle
            - "flip": Mirror image horizontally or vertically
            - "brightness": Adjust image brightness
            - "contrast": Adjust image contrast
            - "convert": Convert to different format
            - "filter": Apply image filter
        
        # Resize parameters:
        width: Target width in pixels (for resize).
        height: Target height in pixels (for resize).
        maintain_aspect_ratio: If True, maintain aspect ratio when resizing (default: True).
        
        # Crop parameters:
        left: Left coordinate of crop box (for crop).
        top: Top coordinate of crop box (for crop).
        right: Right coordinate of crop box (for crop).
        bottom: Bottom coordinate of crop box (for crop).
        
        # Rotate parameters:
        angle: Rotation angle in degrees, counter-clockwise (for rotate).
        expand: If True, expand canvas to fit rotated image (for rotate, default: False).
        
        # Flip parameters:
        direction: Flip direction, "horizontal" or "vertical" (for flip).
        
        # Brightness/Contrast parameters:
        factor: Adjustment factor (for brightness/contrast).
            - 1.0 = original
            - < 1.0 = decrease
            - > 1.0 = increase
        
        # Convert parameters:
        format: Target image format (for convert), e.g., "JPEG", "PNG", "BMP", "GIF".
        
        # Filter parameters:
        filter_type: Type of filter to apply (for filter). Valid values:
            - "blur": Blur the image
            - "sharpen": Sharpen the image
            - "edge_enhance": Enhance edges
            - "contour": Find contours
            - "detail": Enhance detail
            - "smooth": Smooth the image
    
    Returns:
        Success: {
            "status": "success",
            "result": {
                "output_path": str,
                "operation": str,
                "details": dict with operation-specific information
            }
        }
        Error: {
            "status": "error",
            "error_message": str
        }
    """
    # Check if PIL is available
    if Image is None:
        return {
            "status": "error",
            "error_message": "PIL/Pillow library is not available. Please ensure it is installed."
        }
    
    # Validate input file
    if not os.path.exists(image_path):
        return {
            "status": "error",
            "error_message": f"Input image file not found: {image_path}"
        }
    
    # Validate operation
    valid_operations = ["resize", "crop", "rotate", "flip", "brightness", "contrast", "convert", "filter"]
    if operation not in valid_operations:
        return {
            "status": "error",
            "error_message": f"Invalid operation '{operation}'. Valid operations: {', '.join(valid_operations)}"
        }
    
    try:
        # Open the image
        img = Image.open(image_path)
        original_format = img.format
        details = {}
        
        # Perform the requested operation
        if operation == "resize":
            if width is None and height is None:
                return {
                    "status": "error",
                    "error_message": "Resize operation requires 'width' and/or 'height' parameters"
                }
            
            original_width, original_height = img.size
            
            if maintain_aspect_ratio:
                if width and height:
                    # Use thumbnail to maintain aspect ratio within bounds
                    img.thumbnail((width, height), Image.Resampling.LANCZOS)
                elif width:
                    # Calculate height based on width
                    ratio = width / original_width
                    height = int(original_height * ratio)
                    img = img.resize((width, height), Image.Resampling.LANCZOS)
                else:  # height only
                    # Calculate width based on height
                    ratio = height / original_height
                    width = int(original_width * ratio)
                    img = img.resize((width, height), Image.Resampling.LANCZOS)
            else:
                if not width or not height:
                    return {
                        "status": "error",
                        "error_message": "When maintain_aspect_ratio is False, both width and height must be specified"
                    }
                img = img.resize((width, height), Image.Resampling.LANCZOS)
            
            details = {
                "original_size": f"{original_width}x{original_height}",
                "new_size": f"{img.size[0]}x{img.size[1]}"
            }
        
        elif operation == "crop":
            if None in (left, top, right, bottom):
                return {
                    "status": "error",
                    "error_message": "Crop operation requires 'left', 'top', 'right', and 'bottom' parameters"
                }
            
            img_width, img_height = img.size
            
            # Validate crop coordinates
            if left < 0 or top < 0 or right > img_width or bottom > img_height or left >= right or top >= bottom:
                return {
                    "status": "error",
                    "error_message": f"Invalid crop coordinates. Image size: {img_width}x{img_height}, Crop box: ({left}, {top}, {right}, {bottom})"
                }
            
            img = img.crop((left, top, right, bottom))
            details = {
                "crop_box": f"({left}, {top}, {right}, {bottom})",
                "cropped_size": f"{img.size[0]}x{img.size[1]}"
            }
        
        elif operation == "rotate":
            if angle is None:
                return {
                    "status": "error",
                    "error_message": "Rotate operation requires 'angle' parameter"
                }
            
            img = img.rotate(angle, expand=expand, resample=Image.Resampling.BICUBIC)
            details = {
                "angle": angle,
                "expanded": expand,
                "new_size": f"{img.size[0]}x{img.size[1]}"
            }
        
        elif operation == "flip":
            if direction not in ["horizontal", "vertical"]:
                return {
                    "status": "error",
                    "error_message": "Flip operation requires 'direction' parameter with value 'horizontal' or 'vertical'"
                }
            
            if direction == "horizontal":
                img = img.transpose(Image.Transpose.FLIP_LEFT_RIGHT)
            else:  # vertical
                img = img.transpose(Image.Transpose.FLIP_TOP_BOTTOM)
            
            details = {"direction": direction}
        
        elif operation == "brightness":
            if factor is None:
                return {
                    "status": "error",
                    "error_message": "Brightness operation requires 'factor' parameter"
                }
            
            if factor < 0:
                return {
                    "status": "error",
                    "error_message": "Brightness factor must be non-negative"
                }
            
            enhancer = ImageEnhance.Brightness(img)
            img = enhancer.enhance(factor)
            details = {"factor": factor}
        
        elif operation == "contrast":
            if factor is None:
                return {
                    "status": "error",
                    "error_message": "Contrast operation requires 'factor' parameter"
                }
            
            if factor < 0:
                return {
                    "status": "error",
                    "error_message": "Contrast factor must be non-negative"
                }
            
            enhancer = ImageEnhance.Contrast(img)
            img = enhancer.enhance(factor)
            details = {"factor": factor}
        
        elif operation == "convert":
            if not format:
                return {
                    "status": "error",
                    "error_message": "Convert operation requires 'format' parameter"
                }
            
            format = format.upper()
            valid_formats = ["JPEG", "PNG", "BMP", "GIF", "TIFF", "WEBP", "ICO"]
            if format not in valid_formats:
                return {
                    "status": "error",
                    "error_message": f"Unsupported format '{format}'. Valid formats: {', '.join(valid_formats)}"
                }
            
            # Convert RGBA to RGB for JPEG
            if format == "JPEG" and img.mode in ("RGBA", "LA", "P"):
                background = Image.new("RGB", img.size, (255, 255, 255))
                if img.mode == "P":
                    img = img.convert("RGBA")
                background.paste(img, mask=img.split()[-1] if img.mode == "RGBA" else None)
                img = background
            
            details = {
                "original_format": original_format,
                "new_format": format
            }
        
        elif operation == "filter":
            if not filter_type:
                return {
                    "status": "error",
                    "error_message": "Filter operation requires 'filter_type' parameter"
                }
            
            filter_map = {
                "blur": ImageFilter.BLUR,
                "sharpen": ImageFilter.SHARPEN,
                "edge_enhance": ImageFilter.EDGE_ENHANCE,
                "contour": ImageFilter.CONTOUR,
                "detail": ImageFilter.DETAIL,
                "smooth": ImageFilter.SMOOTH
            }
            
            if filter_type not in filter_map:
                return {
                    "status": "error",
                    "error_message": f"Invalid filter type '{filter_type}'. Valid types: {', '.join(filter_map.keys())}"
                }
            
            img = img.filter(filter_map[filter_type])
            details = {"filter_type": filter_type}
        
        # Ensure output directory exists
        output_dir = os.path.dirname(output_path)
        if output_dir:
            Path(output_dir).mkdir(parents=True, exist_ok=True)
        
        # Save the edited image
        if operation == "convert" and format:
            img.save(output_path, format=format)
        else:
            img.save(output_path)
        
        return {
            "status": "success",
            "result": {
                "output_path": output_path,
                "operation": operation,
                "details": details
            }
        }
    
    except Exception as e:
        return {
            "status": "error",
            "error_message": f"Error processing image: {str(e)}"
        }
