# Generated by NeuroStack
# Vendored from platform origin: tool/fetch_ticket_tools (upstream_version=platform)

"""
Generated Tools - fetch_ticket_tools.py

Auto-generated tools created by the Tool Generator.
Generated on: 2024-11-03 18:39:00
Total tools: 1
Category: JIRA
"""

import requests
from typing import Any, Dict

from .jira_tools import resolve_jira_credentials
from google.adk.tools import ToolContext

def fetch_ticket(
    ticket_id: str, tool_context: ToolContext | None = None
) -> Dict[str, Any]:
    """
    Retrieves a JIRA ticket by ID and returns relevant information.

    Args:
        ticket_id (str): The ID of the JIRA ticket.

    Returns:
        Dict[str, Any]: A dictionary containing the ticket details or an error message.
    """
    try:
        if tool_context is None:
            raise ValueError("Jira credentials require an authenticated tool context")
        jira_base_url, jira_email, jira_api_token = resolve_jira_credentials(tool_context)

        api_url = f"{jira_base_url}/rest/api/3/issue/{ticket_id}"
        auth = (jira_email, jira_api_token)

        response = requests.get(api_url, auth=auth)
        response.raise_for_status()  # Raise HTTPError for bad responses (4xx or 5xx)

        if response.status_code == 200:
            ticket_data = response.json()

            # Extract description as plain text (handle Atlassian Document Format)
            description = ""
            if "fields" in ticket_data and "description" in ticket_data["fields"]:
                description_content = ticket_data["fields"]["description"]
                if description_content and isinstance(description_content, dict) and "content" in description_content:
                  description_parts = description_content["content"]
                  description = "\n".join([part["text"] for part in description_parts if part["type"] == "text"])

            comments = []
            if "fields" in ticket_data and "comment" in ticket_data["fields"] and "comments" in ticket_data["fields"]["comment"]:
              comments_data = ticket_data["fields"]["comment"]["comments"]
              comments = [comment["body"]["content"][0]["text"] for comment in comments_data if comment["body"]["content"][0]["type"] == "text"]

            # Extracting Reporter Email
            reporter_email = ""
            if "fields" in ticket_data and "reporter" in ticket_data["fields"] and "emailAddress" in ticket_data["fields"]["reporter"]:
                reporter_email = ticket_data["fields"]["reporter"]["emailAddress"]

            # Extracting Priority
            priority = ""
            if "fields" in ticket_data and "priority" in ticket_data["fields"] and "name" in ticket_data["fields"]["priority"]:
                priority = ticket_data["fields"]["priority"]["name"]
            
            # Extracting Status
            status = ""
            if "fields" in ticket_data and "status" in ticket_data["fields"] and "name" in ticket_data["fields"]["status"]:
                status = ticket_data["fields"]["status"]["name"]

            formatted_ticket = {
                "id": ticket_data["key"],
                "summary": ticket_data["fields"]["summary"],
                "description": description,
                "priority": priority,
                "status": status,
                "reporter_email": reporter_email,
                "created_at": ticket_data["fields"]["created"],
                "comments": comments
            }

            return {
                "success": True,
                "message": "Ticket retrieved successfully.",
                "data": formatted_ticket
            }

        else:
            return {
                "success": False,
                "message": f"Error: Received status code {response.status_code}",
                "data": {}
            }

    except requests.exceptions.HTTPError as e:
        if e.response.status_code == 404:
            return {
                "success": False,
                "message": "Ticket not found.",
                "data": {}
            }
        elif e.response.status_code == 401:
            return {
                "success": False,
                "message": "Authentication failed.",
                "data": {}
            }
        else:
            return {
                "success": False,
                "message": f"Error: {str(e)}",
                "data": {}
            }
    except Exception as e:
        return {
            "success": False,
            "message": f"Error: {str(e)}",
            "data": {}
        }
