# Generated by NeuroStack
# Artifact: tool/get_weather_forecast.py

"""Weather forecasting tool using OpenWeatherMap API.

Fetches current weather conditions for a specified location.
Use this tool when you need to provide weather information to users.
"""

import os
from dotenv import load_dotenv
import httpx

# Load environment variables from .env file
load_dotenv(override=True)


async def get_weather_forecast(location: str, units: str = "metric") -> dict:
    """Fetch current weather forecast for a location.
    
    Use this tool to get current weather conditions including temperature,
    humidity, wind speed, and weather description for any city worldwide.
    
    Args:
        location: City name or "city,country_code" format (e.g., "London", "Tokyo,JP")
        units: Temperature units - "metric" (Celsius), "imperial" (Fahrenheit), 
               or "kelvin". Default: "metric"
    
    Returns:
        Success dict with weather data:
        {
            "status": "success",
            "result": {
                "location": str,
                "current": str,
                "description": str,
                "temperature": float,
                "feels_like": float,
                "humidity": int,
                "wind_speed": float,
                "units": str
            }
        }
        
        Error dict:
        {
            "status": "error",
            "error_message": str
        }
    """
    # Validate API key is present
    api_key = os.getenv("OPENWEATHERMAP_API_KEY")
    if not api_key:
        return {
            "status": "error",
            "error_message": "OPENWEATHERMAP_API_KEY environment variable is not set. "
                           "Please sign up for a free API key at openweathermap.org "
                           "and add it to your .env file."
        }
    
    # Validate units parameter
    valid_units = ["metric", "imperial", "kelvin"]
    if units not in valid_units:
        return {
            "status": "error",
            "error_message": f"Invalid units '{units}'. Must be one of: {', '.join(valid_units)}"
        }
    
    # Build API request
    base_url = "https://api.openweathermap.org/data/2.5/weather"
    params = {
        "q": location,
        "appid": api_key,
        "units": units
    }
    
    try:
        async with httpx.AsyncClient(timeout=10.0) as client:
            response = await client.get(base_url, params=params)
            
            # Handle specific HTTP errors
            if response.status_code == 404:
                return {
                    "status": "error",
                    "error_message": f"Location '{location}' not found. "
                                   "Please check the spelling or try 'city,country_code' format."
                }
            elif response.status_code == 401:
                return {
                    "status": "error",
                    "error_message": "Invalid API key. Please check your OPENWEATHERMAP_API_KEY."
                }
            elif response.status_code == 429:
                return {
                    "status": "error",
                    "error_message": "API rate limit exceeded. Free tier allows 60 calls per minute. "
                                   "Please wait a moment and try again."
                }
            elif response.status_code != 200:
                return {
                    "status": "error",
                    "error_message": f"Weather API returned error: {response.status_code} - {response.text}"
                }
            
            # Parse successful response
            data = response.json()
            
            # Determine unit labels
            temp_unit = "°C" if units == "metric" else "°F" if units == "imperial" else "K"
            speed_unit = "m/s" if units == "metric" else "mph" if units == "imperial" else "m/s"
            
            # Build result
            result = {
                "location": data.get("name", location),
                "current": data["weather"][0]["main"],
                "description": data["weather"][0]["description"],
                "temperature": round(data["main"]["temp"], 1),
                "feels_like": round(data["main"]["feels_like"], 1),
                "humidity": data["main"]["humidity"],
                "wind_speed": round(data["wind"]["speed"], 1),
                "units": f"Temperature in {temp_unit}, Wind speed in {speed_unit}"
            }
            
            return {
                "status": "success",
                "result": result
            }
            
    except httpx.TimeoutException:
        return {
            "status": "error",
            "error_message": "Request timed out. Please check your internet connection and try again."
        }
    except httpx.RequestError as e:
        return {
            "status": "error",
            "error_message": f"Network error: {str(e)}"
        }
    except KeyError as e:
        return {
            "status": "error",
            "error_message": f"Unexpected API response format: missing field {str(e)}"
        }
    except Exception as e:
        return {
            "status": "error",
            "error_message": f"Unexpected error: {str(e)}"
        }
