# Generated by NeuroStack
# Artifact: tool/investment_planning.py

"""Investment planning tool for portfolio analysis and retirement projections.

Calculates optimal asset allocation, analyzes portfolio balance, projects growth,
and provides personalized investment recommendations based on risk tolerance and goals.
"""

import math
from typing import Optional


async def calculate_investment_plan(
    current_age: int,
    retirement_age: int,
    risk_tolerance: str,
    current_portfolio: dict,
    monthly_contribution: float,
    expected_return_rate: Optional[float] = None,
    inflation_rate: float = 0.03
) -> dict:
    """Calculate comprehensive investment plan with allocation recommendations and projections.
    
    Use this tool when users need investment planning guidance, portfolio analysis,
    retirement projections, or asset allocation recommendations.
    
    Args:
        current_age: User's current age in years (must be positive and less than retirement_age)
        retirement_age: Target retirement age in years (must be greater than current_age)
        risk_tolerance: Risk profile - must be "conservative", "moderate", or "aggressive"
        current_portfolio: Dictionary of asset types and current values in USD,
            e.g., {"stocks": 50000, "bonds": 30000, "cash": 10000}
        monthly_contribution: Amount to invest monthly in USD (can be 0)
        expected_return_rate: Optional custom expected annual return as decimal (e.g., 0.07 for 7%).
            If not provided, defaults based on risk_tolerance
        inflation_rate: Annual inflation rate as decimal for real return calculations (default 0.03 for 3%)
    
    Returns:
        Success dict with:
            - recommended_allocation: Target allocation percentages by asset type
            - current_allocation: Current allocation percentages
            - rebalancing_needed: Boolean indicating if rebalancing recommended
            - rebalancing_actions: Dollar amounts to adjust for each asset type
            - projection: Future value estimates with contributions and growth breakdown
            - risk_metrics: Diversification score, volatility level, time horizon
            - recommendations: List of personalized recommendations
        
        Error dict with error_message on validation or calculation failure
    """
    
    try:
        # Validate inputs
        if not isinstance(current_age, int) or current_age <= 0:
            return {
                "status": "error",
                "error_message": "current_age must be a positive integer"
            }
        
        if not isinstance(retirement_age, int) or retirement_age <= 0:
            return {
                "status": "error",
                "error_message": "retirement_age must be a positive integer"
            }
        
        if current_age >= retirement_age:
            return {
                "status": "error",
                "error_message": "current_age must be less than retirement_age"
            }
        
        risk_tolerance = risk_tolerance.lower()
        valid_risk_levels = ["conservative", "moderate", "aggressive"]
        if risk_tolerance not in valid_risk_levels:
            return {
                "status": "error",
                "error_message": f"risk_tolerance must be one of: {', '.join(valid_risk_levels)}"
            }
        
        if not isinstance(current_portfolio, dict):
            return {
                "status": "error",
                "error_message": "current_portfolio must be a dictionary"
            }
        
        # Validate portfolio values
        for asset, value in current_portfolio.items():
            if not isinstance(value, (int, float)) or value < 0:
                return {
                    "status": "error",
                    "error_message": f"Portfolio value for {asset} must be a non-negative number"
                }
        
        if monthly_contribution < 0:
            return {
                "status": "error",
                "error_message": "monthly_contribution must be non-negative"
            }
        
        if expected_return_rate is not None:
            if not (0 <= expected_return_rate <= 1):
                return {
                    "status": "error",
                    "error_message": "expected_return_rate must be between 0 and 1 (e.g., 0.07 for 7%)"
                }
        
        if not (0 <= inflation_rate <= 1):
            return {
                "status": "error",
                "error_message": "inflation_rate must be between 0 and 1"
            }
        
        # Calculate time horizon
        years_to_retirement = retirement_age - current_age
        
        # Determine expected return rate if not provided
        if expected_return_rate is None:
            return_rates = {
                "conservative": 0.05,
                "moderate": 0.07,
                "aggressive": 0.09
            }
            expected_return_rate = return_rates[risk_tolerance]
        
        # Define target allocations based on risk tolerance
        base_allocations = {
            "conservative": {"stocks": 0.40, "bonds": 0.50, "cash": 0.10},
            "moderate": {"stocks": 0.60, "bonds": 0.30, "cash": 0.10},
            "aggressive": {"stocks": 0.80, "bonds": 0.15, "cash": 0.05}
        }
        
        recommended_allocation = base_allocations[risk_tolerance].copy()
        
        # Adjust for short time horizon (under 10 years)
        if years_to_retirement < 10:
            # Reduce stock allocation and increase bonds/cash for shorter horizons
            reduction = (10 - years_to_retirement) * 0.03
            recommended_allocation["stocks"] = max(0.20, recommended_allocation["stocks"] - reduction)
            
            # Distribute reduction to bonds and cash
            bonds_increase = reduction * 0.7
            cash_increase = reduction * 0.3
            recommended_allocation["bonds"] = min(0.70, recommended_allocation["bonds"] + bonds_increase)
            recommended_allocation["cash"] = min(0.30, recommended_allocation["cash"] + cash_increase)
            
            # Normalize to ensure sum is 1.0
            total = sum(recommended_allocation.values())
            recommended_allocation = {k: v / total for k, v in recommended_allocation.items()}
        
        # Calculate current portfolio total and allocation
        current_total = sum(current_portfolio.values())
        
        if current_total == 0:
            current_allocation = {"stocks": 0.0, "bonds": 0.0, "cash": 0.0}
        else:
            current_allocation = {
                asset: value / current_total
                for asset, value in current_portfolio.items()
            }
            
            # Ensure all asset types are present
            for asset in ["stocks", "bonds", "cash"]:
                if asset not in current_allocation:
                    current_allocation[asset] = 0.0
        
        # Calculate rebalancing needs
        rebalancing_threshold = 0.05
        rebalancing_needed = False
        rebalancing_actions = {}
        
        for asset in ["stocks", "bonds", "cash"]:
            current = current_allocation.get(asset, 0.0)
            target = recommended_allocation.get(asset, 0.0)
            
            if abs(current - target) > rebalancing_threshold:
                rebalancing_needed = True
            
            # Calculate dollar amount to adjust
            if current_total > 0:
                target_value = target * current_total
                current_value = current_portfolio.get(asset, 0.0)
                adjustment = target_value - current_value
                
                if adjustment > 0:
                    rebalancing_actions[asset] = f"+${adjustment:,.0f}"
                elif adjustment < 0:
                    rebalancing_actions[asset] = f"-${abs(adjustment):,.0f}"
                else:
                    rebalancing_actions[asset] = "$0"
            else:
                rebalancing_actions[asset] = "N/A"
        
        # Calculate future value projection
        # Formula: FV = PV(1+r)^n + PMT × [((1+r)^n - 1) / r]
        monthly_rate = expected_return_rate / 12
        months = years_to_retirement * 12
        
        # Present value growth
        if current_total > 0:
            pv_growth = current_total * math.pow(1 + monthly_rate, months)
        else:
            pv_growth = 0
        
        # Future value of monthly contributions
        if monthly_contribution > 0 and monthly_rate > 0:
            fv_contributions = monthly_contribution * ((math.pow(1 + monthly_rate, months) - 1) / monthly_rate)
        else:
            fv_contributions = monthly_contribution * months
        
        projected_total = pv_growth + fv_contributions
        total_contributions = monthly_contribution * months
        investment_growth = projected_total - current_total - total_contributions
        
        # Calculate inflation-adjusted real value
        real_value_adjusted = projected_total / math.pow(1 + inflation_rate, years_to_retirement)
        
        # Calculate diversification score (0-1, higher is better)
        # Based on how evenly distributed the allocation is
        allocation_values = list(current_allocation.values())
        if sum(allocation_values) > 0:
            # Use inverse of Herfindahl index, normalized
            herfindahl = sum(x * x for x in allocation_values)
            max_herfindahl = 1.0  # All in one asset
            min_herfindahl = 1.0 / 3  # Evenly distributed across 3 assets
            diversification_score = 1 - ((herfindahl - min_herfindahl) / (max_herfindahl - min_herfindahl))
            diversification_score = max(0, min(1, diversification_score))
        else:
            diversification_score = 0.0
        
        # Determine volatility level
        volatility_mapping = {
            "conservative": "low",
            "moderate": "moderate",
            "aggressive": "high"
        }
        volatility_level = volatility_mapping[risk_tolerance]
        
        # Determine time horizon category
        if years_to_retirement < 5:
            time_horizon = "short"
        elif years_to_retirement < 15:
            time_horizon = "medium"
        else:
            time_horizon = "long"
        
        # Generate personalized recommendations
        recommendations = []
        
        # Allocation recommendations
        for asset in ["stocks", "bonds", "cash"]:
            current = current_allocation.get(asset, 0.0)
            target = recommended_allocation.get(asset, 0.0)
            diff = target - current
            
            if abs(diff) > rebalancing_threshold:
                direction = "Increase" if diff > 0 else "Decrease"
                recommendations.append(
                    f"{direction} {asset} allocation by {abs(diff)*100:.0f}% to match risk tolerance"
                )
        
        # Time horizon recommendations
        if years_to_retirement < 5:
            recommendations.append(
                "With retirement approaching, consider gradually shifting to more conservative allocations"
            )
        elif years_to_retirement > 20:
            recommendations.append(
                "Your long time horizon allows for growth-oriented investments"
            )
        
        # Contribution recommendations
        if monthly_contribution == 0:
            recommendations.append(
                "Consider adding regular monthly contributions to accelerate portfolio growth"
            )
        elif monthly_contribution < 500:
            recommendations.append(
                "Increasing monthly contributions, even slightly, can significantly impact long-term outcomes"
            )
        
        # Diversification recommendations
        if diversification_score < 0.5:
            recommendations.append(
                "Your portfolio is concentrated in few assets; consider diversifying for better risk management"
            )
        elif diversification_score > 0.8:
            recommendations.append(
                "Your portfolio shows good diversification across asset classes"
            )
        
        # General recommendations
        if not rebalancing_needed:
            recommendations.append(
                "Your portfolio allocation is well-aligned with your target"
            )
        
        recommendations.append(
            "Review and rebalance your portfolio at least annually or when allocations drift significantly"
        )
        
        # Build result
        result = {
            "recommended_allocation": {
                asset: round(value, 4)
                for asset, value in recommended_allocation.items()
            },
            "current_allocation": {
                asset: round(value, 4)
                for asset, value in current_allocation.items()
            },
            "rebalancing_needed": rebalancing_needed,
            "rebalancing_actions": rebalancing_actions,
            "projection": {
                "years_to_retirement": years_to_retirement,
                "current_total": round(current_total, 2),
                "projected_total": round(projected_total, 2),
                "total_contributions": round(total_contributions, 2),
                "investment_growth": round(investment_growth, 2),
                "real_value_adjusted": round(real_value_adjusted, 2)
            },
            "risk_metrics": {
                "portfolio_diversification_score": round(diversification_score, 2),
                "volatility_level": volatility_level,
                "time_horizon": time_horizon
            },
            "recommendations": recommendations
        }
        
        return {
            "status": "success",
            "result": result
        }
    
    except ZeroDivisionError:
        return {
            "status": "error",
            "error_message": "Mathematical error in calculation (division by zero)"
        }
    except OverflowError:
        return {
            "status": "error",
            "error_message": "Values too large to calculate - please verify inputs"
        }
    except Exception as e:
        return {
            "status": "error",
            "error_message": f"Unexpected error during calculation: {str(e)}"
        }
