# Generated by NeuroStack
# Vendored from platform origin: tool/jira_tools (upstream_version=platform)

"""
Generated Tools - jira_tools.py

Auto-generated tools created by the Tool Generator.
Generated on: 2024-02-29 17:34:00
Total tools: 1
"""

import requests
from typing import Any, Dict, Tuple

from google.adk.tools import ToolContext

from ..connectors.secrets import SecretResolutionError, get_default_resolver
from ..tenancy.repository import TenantCredentialRepository


def resolve_jira_credentials(tool_context: ToolContext) -> Tuple[str, str, str]:
    """Resolve the authenticated user's tenant-owned Jira references."""
    from ..api.models.authentication_models import User
    from ..core.database import SessionLocal

    user_id = str(getattr(tool_context, "user_id", "") or "").strip()
    if not user_id:
        raise ValueError("Jira credentials require an authenticated user context")

    db = SessionLocal()
    try:
        user = db.query(User).filter(User.id == user_id).first()
        if user is None or not user.is_active:
            raise ValueError("The authenticated Jira user is unavailable")

        tenant_id = str(user.tenant_id or "").strip()
        if not tenant_id:
            raise ValueError("The authenticated user has no tenant configured")

        refs = TenantCredentialRepository(db)
        references = {}
        resolved = {}
        for key in ("JIRA_URL", "JIRA_USERNAME", "JIRA_API_TOKEN"):
            reference = refs.get_ref(tenant_id, key)
            if not reference:
                raise ValueError(
                    f"Tenant Jira credential '{key}' is not configured"
                )
            references[key] = reference

        resolver = get_default_resolver()
        for key, reference in references.items():
            try:
                resolved[key] = resolver.resolve(reference)
            except SecretResolutionError as exc:
                raise ValueError(
                    f"Tenant Jira credential '{key}' could not be resolved"
                ) from exc

        return (
            resolved["JIRA_URL"].rstrip("/"),
            resolved["JIRA_USERNAME"],
            resolved["JIRA_API_TOKEN"],
        )
    finally:
        db.close()

def update_jira_ticket(
    ticket_id: str,
    status: str,
    resolution_note: str,
    draft_response: str = "",
    tool_context: ToolContext | None = None,
) -> Dict[str, Any]:
    """
    Updates a JIRA ticket status and adds a comment.

    Args:
        ticket_id (str): The ID of the JIRA ticket to update.
        status (str): The desired status of the ticket ("resolved" or "closed" trigger transition).
        resolution_note (str): The note to add as a comment to the ticket.
        draft_response (str, optional): An optional draft response to add as a separate comment. Defaults to "".

    Returns:
        Dict[str, Any]: A dictionary containing the success status, message, and data about the operation.
                         Example: {"success": True, "message": "Ticket updated successfully", "data": {"ticket_id": "JIRA-123", "status_updated": True, "comment_added": True}}
    """
    try:
        if tool_context is None:
            raise ValueError("Jira credentials require an authenticated tool context")
        jira_base_url, jira_email, jira_api_token = resolve_jira_credentials(tool_context)

        # 1. Add Resolution Note as Comment
        comment_url = f"{jira_base_url}/rest/api/3/issue/{ticket_id}/comment"
        comment_payload = {
            "body": {
                "type": "doc",
                "version": 1,
                "content": [
                    {
                        "type": "paragraph",
                        "content": [
                            {"type": "text", "text": resolution_note}
                        ]
                    }
                ]
            }
        }
        comment_response = requests.post(comment_url, auth=(jira_email, jira_api_token), json=comment_payload)
        comment_response.raise_for_status()  # Raise HTTPError for bad responses (4xx or 5xx)
        comment_added = comment_response.status_code == 201

        # 2. Update Ticket Status (if resolved/closed)
        status_updated = False
        if status.lower() in ("resolved", "closed"):
            transitions_url = f"{jira_base_url}/rest/api/3/issue/{ticket_id}/transitions"
            transitions_response = requests.get(transitions_url, auth=(jira_email, jira_api_token))
            transitions_response.raise_for_status()
            transitions_data = transitions_response.json()

            transition_id = None
            for transition in transitions_data.get("transitions", []):
                if transition.get("name", "").lower() in ("done", "closed"):
                    transition_id = transition.get("id")
                    break

            if transition_id:
                transition_payload = {"transition": {"id": transition_id}}
                transition_url = f"{jira_base_url}/rest/api/3/issue/{ticket_id}/transitions"
                transition_response = requests.post(transition_url, auth=(jira_email, jira_api_token), json=transition_payload)
                transition_response.raise_for_status()
                status_updated = transition_response.status_code == 204
            else:
                return {
                    "success": False,
                    "message": f"No suitable transition found for status '{status}' (Done/Closed)",
                    "data": {"ticket_id": ticket_id, "status_updated": False, "comment_added": comment_added}
                }

        # 3. Add Draft Response as Comment (if provided)
        if draft_response:
            draft_comment_url = f"{jira_base_url}/rest/api/3/issue/{ticket_id}/comment"
            draft_comment_payload = {
                "body": {
                    "type": "doc",
                    "version": 1,
                    "content": [
                        {
                            "type": "paragraph",
                            "content": [{"type": "text", "text": draft_response}]
                        }
                    ]
                }
            }
            draft_comment_response = requests.post(draft_comment_url, auth=(jira_email, jira_api_token), json=draft_comment_payload)
            draft_comment_response.raise_for_status()
            comment_added = comment_added and (draft_comment_response.status_code == 201) #Ensure both comments were added

        return {
            "success": True,
            "message": "Ticket updated successfully",
            "data": {"ticket_id": ticket_id, "status_updated": status_updated, "comment_added": comment_added}
        }

    except requests.exceptions.RequestException as e:
        return {
            "success": False,
            "message": f"Request failed: {str(e)}",
            "data": {}
        }
    except Exception as e:
        return {
            "success": False,
            "message": f"An unexpected error occurred: {str(e)}",
            "data": {}
        }
