# Generated by NeuroStack
# Artifact: tool/manage_ado_board.py

"""Azure DevOps board management tool.

Manages Azure DevOps boards with work item operations, queries, and board configuration.
"""

import os
import base64
from typing import Dict, Any, Optional
from dotenv import load_dotenv

# Load environment variables before any usage
load_dotenv(override=True)

from azure.devops.connection import Connection
from msrest.authentication import BasicAuthentication
from azure.devops.v7_0.work_item_tracking.models import Wiql, JsonPatchOperation
import requests


async def manage_ado_board(
    organization_url: str,
    project: str,
    operation: str,
    personal_access_token: Optional[str] = None,
    team: Optional[str] = None,
    work_item_type: Optional[str] = None,
    work_item_id: Optional[int] = None,
    fields: Optional[Dict[str, Any]] = None,
    wiql_query: Optional[str] = None,
    board_name: Optional[str] = None,
    swimlane_name: Optional[str] = None
) -> Dict[str, Any]:
    """Manage Azure DevOps boards and work items.
    
    Performs operations on Azure DevOps boards including work item management,
    queries, board column retrieval, and swimlane updates. Use this tool to
    interact programmatically with Azure DevOps boards.
    
    Args:
        organization_url: Azure DevOps organization URL (e.g., https://dev.azure.com/myorg).
        project: Project name.
        operation: Operation to perform. One of:
            - create_work_item: Create a new work item
            - update_work_item: Update an existing work item
            - get_work_item: Retrieve a work item by ID
            - query_work_items: Query work items using WIQL
            - get_board_columns: Retrieve board columns configuration
            - move_to_swimlane: Move a work item to a swimlane
        personal_access_token: PAT for authentication. Defaults to AZURE_DEVOPS_PAT env var.
        team: Team name (required for board operations).
        work_item_type: Work item type like Bug, Task, User Story (required for create_work_item).
        work_item_id: Work item ID (required for update_work_item, get_work_item, move_to_swimlane).
        fields: Dictionary of field values for create/update operations.
            Example: {"System.Title": "Bug fix", "System.Description": "Details here"}
        wiql_query: WIQL query string (required for query_work_items).
            Example: "SELECT [System.Id], [System.Title] FROM WorkItems WHERE [System.State] = 'Active'"
        board_name: Board name (required for get_board_columns and move_to_swimlane).
        swimlane_name: Target swimlane name (required for move_to_swimlane).
    
    Returns:
        Success: {"status": "success", "result": <operation-specific data>}
        Error: {"status": "error", "error_message": "..."}
    """
    try:
        # Validate operation
        valid_operations = [
            "create_work_item", "update_work_item", "get_work_item",
            "query_work_items", "get_board_columns", "move_to_swimlane"
        ]
        if operation not in valid_operations:
            return {
                "status": "error",
                "error_message": f"Invalid operation '{operation}'. Must be one of: {', '.join(valid_operations)}"
            }
        
        # Get PAT from parameter or environment variable
        pat = personal_access_token or os.getenv("AZURE_DEVOPS_PAT")
        if not pat:
            return {
                "status": "error",
                "error_message": "Personal access token required. Provide via parameter or AZURE_DEVOPS_PAT environment variable."
            }
        
        # Validate organization URL
        if not organization_url.startswith("https://"):
            return {
                "status": "error",
                "error_message": "Organization URL must start with https://"
            }
        
        # Create Azure DevOps connection
        credentials = BasicAuthentication('', pat)
        connection = Connection(base_url=organization_url, credentials=credentials)
        wit_client = connection.clients.get_work_item_tracking_client()
        
        # Route to appropriate operation
        if operation == "create_work_item":
            return await _create_work_item(wit_client, project, work_item_type, fields)
        
        elif operation == "update_work_item":
            return await _update_work_item(wit_client, work_item_id, fields)
        
        elif operation == "get_work_item":
            return await _get_work_item(wit_client, work_item_id)
        
        elif operation == "query_work_items":
            return await _query_work_items(wit_client, project, wiql_query)
        
        elif operation == "get_board_columns":
            return await _get_board_columns(organization_url, project, team, board_name, pat)
        
        elif operation == "move_to_swimlane":
            return await _move_to_swimlane(
                wit_client, organization_url, project, team, 
                board_name, work_item_id, swimlane_name, pat
            )
        
    except Exception as e:
        return {
            "status": "error",
            "error_message": f"Unexpected error in manage_ado_board: {str(e)}"
        }


async def _create_work_item(
    wit_client,
    project: str,
    work_item_type: Optional[str],
    fields: Optional[Dict[str, Any]]
) -> Dict[str, Any]:
    """Create a new work item."""
    try:
        if not work_item_type:
            return {
                "status": "error",
                "error_message": "work_item_type is required for create_work_item operation"
            }
        
        if not fields:
            return {
                "status": "error",
                "error_message": "fields dictionary is required for create_work_item operation"
            }
        
        # Build JSON patch document
        document = []
        for field_path, value in fields.items():
            document.append(JsonPatchOperation(
                op='add',
                path=f'/fields/{field_path}',
                value=value
            ))
        
        # Create work item
        work_item = wit_client.create_work_item(
            document=document,
            project=project,
            type=work_item_type
        )
        
        return {
            "status": "success",
            "result": {
                "id": work_item.id,
                "url": work_item.url,
                "fields": work_item.fields
            }
        }
    
    except Exception as e:
        return {
            "status": "error",
            "error_message": f"Failed to create work item: {str(e)}"
        }


async def _update_work_item(
    wit_client,
    work_item_id: Optional[int],
    fields: Optional[Dict[str, Any]]
) -> Dict[str, Any]:
    """Update an existing work item."""
    try:
        if work_item_id is None:
            return {
                "status": "error",
                "error_message": "work_item_id is required for update_work_item operation"
            }
        
        if not fields:
            return {
                "status": "error",
                "error_message": "fields dictionary is required for update_work_item operation"
            }
        
        # Build JSON patch document
        document = []
        for field_path, value in fields.items():
            # Use 'add' operation which works for both new and existing fields
            document.append(JsonPatchOperation(
                op='add',
                path=f'/fields/{field_path}',
                value=value
            ))
        
        # Update work item
        work_item = wit_client.update_work_item(
            document=document,
            id=work_item_id
        )
        
        return {
            "status": "success",
            "result": {
                "id": work_item.id,
                "url": work_item.url,
                "fields": work_item.fields
            }
        }
    
    except Exception as e:
        return {
            "status": "error",
            "error_message": f"Failed to update work item: {str(e)}"
        }


async def _get_work_item(
    wit_client,
    work_item_id: Optional[int]
) -> Dict[str, Any]:
    """Retrieve a work item by ID."""
    try:
        if work_item_id is None:
            return {
                "status": "error",
                "error_message": "work_item_id is required for get_work_item operation"
            }
        
        # Get work item
        work_item = wit_client.get_work_item(work_item_id)
        
        return {
            "status": "success",
            "result": {
                "id": work_item.id,
                "url": work_item.url,
                "fields": work_item.fields,
                "relations": work_item.relations
            }
        }
    
    except Exception as e:
        return {
            "status": "error",
            "error_message": f"Failed to get work item: {str(e)}"
        }


async def _query_work_items(
    wit_client,
    project: str,
    wiql_query: Optional[str]
) -> Dict[str, Any]:
    """Query work items using WIQL."""
    try:
        if not wiql_query:
            return {
                "status": "error",
                "error_message": "wiql_query is required for query_work_items operation"
            }
        
        # Execute WIQL query
        wiql = Wiql(query=wiql_query)
        query_results = wit_client.query_by_wiql(wiql=wiql, project=project)
        
        # Extract work item IDs
        work_item_ids = []
        if query_results.work_items:
            work_item_ids = [item.id for item in query_results.work_items]
        elif query_results.work_item_relations:
            work_item_ids = [relation.target.id for relation in query_results.work_item_relations]
        
        # Fetch full work item details if IDs found
        work_items = []
        if work_item_ids:
            # Batch fetch work items (limit to 200 per batch as per API limits)
            for i in range(0, len(work_item_ids), 200):
                batch_ids = work_item_ids[i:i+200]
                batch_items = wit_client.get_work_items(ids=batch_ids)
                work_items.extend([{
                    "id": item.id,
                    "url": item.url,
                    "fields": item.fields
                } for item in batch_items])
        
        return {
            "status": "success",
            "result": {
                "count": len(work_items),
                "work_items": work_items
            }
        }
    
    except Exception as e:
        return {
            "status": "error",
            "error_message": f"Failed to query work items: {str(e)}"
        }


async def _get_board_columns(
    organization_url: str,
    project: str,
    team: Optional[str],
    board_name: Optional[str],
    pat: str
) -> Dict[str, Any]:
    """Retrieve board columns configuration using REST API."""
    try:
        if not team:
            return {
                "status": "error",
                "error_message": "team is required for get_board_columns operation"
            }
        
        if not board_name:
            return {
                "status": "error",
                "error_message": "board_name is required for get_board_columns operation"
            }
        
        # Encode PAT for Basic Authentication
        encoded_pat = base64.b64encode(f":{pat}".encode()).decode()
        headers = {
            "Authorization": f"Basic {encoded_pat}",
            "Content-Type": "application/json"
        }
        
        # Build API URL
        api_url = f"{organization_url}/{project}/{team}/_apis/work/boards/{board_name}/columns?api-version=7.1"
        
        # Make REST API call
        response = requests.get(api_url, headers=headers)
        response.raise_for_status()
        
        columns_data = response.json()
        
        return {
            "status": "success",
            "result": {
                "count": columns_data.get("count", 0),
                "columns": columns_data.get("value", [])
            }
        }
    
    except requests.exceptions.HTTPError as e:
        return {
            "status": "error",
            "error_message": f"HTTP error getting board columns: {e.response.status_code} - {e.response.text}"
        }
    except Exception as e:
        return {
            "status": "error",
            "error_message": f"Failed to get board columns: {str(e)}"
        }


async def _move_to_swimlane(
    wit_client,
    organization_url: str,
    project: str,
    team: Optional[str],
    board_name: Optional[str],
    work_item_id: Optional[int],
    swimlane_name: Optional[str],
    pat: str
) -> Dict[str, Any]:
    """Move a work item to a specific swimlane."""
    try:
        if not team:
            return {
                "status": "error",
                "error_message": "team is required for move_to_swimlane operation"
            }
        
        if not board_name:
            return {
                "status": "error",
                "error_message": "board_name is required for move_to_swimlane operation"
            }
        
        if work_item_id is None:
            return {
                "status": "error",
                "error_message": "work_item_id is required for move_to_swimlane operation"
            }
        
        if not swimlane_name:
            return {
                "status": "error",
                "error_message": "swimlane_name is required for move_to_swimlane operation"
            }
        
        # Step 1: Get board information to find the swimlane field reference name
        encoded_pat = base64.b64encode(f":{pat}".encode()).decode()
        headers = {
            "Authorization": f"Basic {encoded_pat}",
            "Content-Type": "application/json"
        }
        
        board_api_url = f"{organization_url}/{project}/{team}/_apis/work/boards/{board_name}?api-version=7.1"
        
        response = requests.get(board_api_url, headers=headers)
        response.raise_for_status()
        board_data = response.json()
        
        # Extract the rowField reference name (swimlane field with GUID)
        row_field_ref_name = None
        if 'fields' in board_data and 'rowField' in board_data['fields']:
            row_field_ref_name = board_data['fields']['rowField'].get('referenceName')
        
        if not row_field_ref_name:
            return {
                "status": "error",
                "error_message": "Could not find swimlane field (rowField) for the board. The board may not have swimlanes configured."
            }
        
        # Step 2: Update the work item with the swimlane field
        document = [
            JsonPatchOperation(
                op='add',
                path=f'/fields/{row_field_ref_name}',
                value=swimlane_name
            )
        ]
        
        work_item = wit_client.update_work_item(
            document=document,
            id=work_item_id
        )
        
        return {
            "status": "success",
            "result": {
                "id": work_item.id,
                "swimlane_field": row_field_ref_name,
                "swimlane_value": swimlane_name,
                "message": f"Work item {work_item_id} moved to swimlane '{swimlane_name}'"
            }
        }
    
    except requests.exceptions.HTTPError as e:
        return {
            "status": "error",
            "error_message": f"HTTP error moving to swimlane: {e.response.status_code} - {e.response.text}"
        }
    except Exception as e:
        return {
            "status": "error",
            "error_message": f"Failed to move work item to swimlane: {str(e)}"
        }
