# Generated by NeuroStack
# Artifact: tool/meeting_tools.py

"""Meeting analysis tools using LLM for structured transcript summarization."""

import json
import os
from typing import Any, Dict

from dotenv import load_dotenv

# Load environment variables at module level
load_dotenv(override=True)

import litellm


def summarize_meeting(
    transcript: str,
    focus: str = "general",
    max_action_items: int = 10
) -> Dict[str, Any]:
    """
    Analyze a meeting transcript using an LLM and return structured JSON.
    
    Use this tool to extract key information from meeting transcripts, including
    summary points, decisions made, action items, open questions, participants,
    and overall sentiment. The focus parameter allows biasing the analysis toward
    specific aspects (e.g., "hiring", "technical", "general").
    
    Args:
        transcript: The full meeting transcript as plain text.
        focus: Analysis bias - "general", "technical", "hiring", etc. Influences
               what the LLM emphasizes in the summary.
        max_action_items: Maximum number of action items to extract (default 10).
    
    Returns:
        Success case:
            {
                "status": "success",
                "result": {
                    "summary": ["bullet 1", "bullet 2", ...],  # 5-8 bullets
                    "decisions": ["decision 1", ...],
                    "action_items": [
                        {"owner": "name", "task": "description", "due": "date"},
                        ...
                    ],
                    "open_questions": ["question 1", ...],
                    "participants": ["participant 1", ...],
                    "sentiment": "positive"  # one word
                }
            }
        
        Parse failure case:
            {
                "status": "success",
                "success": False,
                "raw_response": "the unparseable LLM response"
            }
        
        Error case:
            {
                "status": "error",
                "error_message": "description of what went wrong"
            }
    """
    # Input validation
    if not transcript or not isinstance(transcript, str) or not transcript.strip():
        return {
            "status": "error",
            "error_message": "transcript must be a non-empty string"
        }
    
    # Read environment variables
    model = os.getenv("LLM_MODEL", "bedrock/us.anthropic.claude-sonnet-4-5-20250929-v1:0")
    proxy_url = os.getenv("LITELLM_PROXY_URL")
    
    # Construct prompts
    system_prompt = "You are a precise meeting analyst. Output strict JSON only, no prose."
    
    user_prompt = f"""Analyze this meeting transcript with a focus on "{focus}".

Extract and return ONLY a JSON object (no markdown, no explanation) with:
- summary: array of 5-8 bullet points
- decisions: array of decisions made
- action_items: array of objects with owner, task, due (limit to {max_action_items})
- open_questions: array of unresolved questions
- participants: array of participant names
- sentiment: single word describing overall sentiment

Transcript:
{transcript}
"""
    
    try:
        # Prepare litellm call
        kwargs = {
            "model": model,
            "messages": [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt}
            ],
            "temperature": 0.2
        }
        
        # Add proxy if configured
        if proxy_url:
            litellm.api_base = proxy_url
        
        # Call LLM
        response = litellm.completion(**kwargs)
        
        # Extract response text
        raw_text = response.choices[0].message.content.strip()
        
        # Parse JSON defensively
        try:
            result = json.loads(raw_text)
            
            # Validate expected fields exist
            required_fields = [
                "summary", "decisions", "action_items",
                "open_questions", "participants", "sentiment"
            ]
            
            if not all(field in result for field in required_fields):
                return {
                    "status": "success",
                    "success": False,
                    "raw_response": raw_text,
                    "error": "Missing required fields in JSON response"
                }
            
            return {
                "status": "success",
                "result": result
            }
            
        except json.JSONDecodeError:
            # Parse failed - return raw response
            return {
                "status": "success",
                "success": False,
                "raw_response": raw_text
            }
    
    except Exception as e:
        return {
            "status": "error",
            "error_message": f"LLM call failed: {str(e)}"
        }
