# Generated by NeuroStack
# Artifact: tool/plan_time_management.py

"""Time management planning tool for organizing tasks into optimized schedules.

This tool helps users create structured time-blocked schedules based on task
priorities, deadlines, and available working hours. It automatically adds buffer
time and breaks, calculates productivity metrics, and provides recommendations
for schedule optimization.
"""

from datetime import datetime, timedelta
from typing import Any


def plan_time_management(
    tasks: list[dict],
    available_hours: float,
    start_time: str = "09:00",
    break_duration_minutes: int = 15,
    buffer_percentage: float = 0.15
) -> dict[str, Any]:
    """Create an optimized time-blocked schedule from a list of tasks.
    
    Organizes tasks by priority and deadline, allocates time blocks with breaks
    and buffer time, identifies capacity issues, and provides scheduling recommendations.
    
    Args:
        tasks: List of task dictionaries, each with:
            - name (str): Task description
            - duration_minutes (int): Estimated time needed
            - priority (str): "high", "medium", or "low"
            - deadline (str, optional): ISO date string (YYYY-MM-DD)
        available_hours: Total hours available for work (e.g., 8.0)
        start_time: Schedule start time in HH:MM format (default "09:00")
        break_duration_minutes: Minutes between tasks (default 15)
        buffer_percentage: Extra time buffer as decimal (default 0.15 = 15%)
    
    Returns:
        Success: {
            "status": "success",
            "result": {
                "schedule": List of time-blocked tasks with start/end times,
                "metrics": Utilization and time statistics,
                "unscheduled_tasks": Tasks that didn't fit with reasons,
                "recommendations": Actionable scheduling suggestions
            }
        }
        Error: {"status": "error", "error_message": str}
    """
    try:
        # Validate inputs
        validation_error = _validate_inputs(
            tasks, available_hours, start_time, break_duration_minutes, buffer_percentage
        )
        if validation_error:
            return {"status": "error", "error_message": validation_error}
        
        # Handle empty task list
        if not tasks:
            return {
                "status": "success",
                "result": {
                    "schedule": [],
                    "metrics": {
                        "total_scheduled_minutes": 0,
                        "total_available_minutes": int(available_hours * 60),
                        "utilization_percentage": 0.0,
                        "unscheduled_tasks": 0,
                        "buffer_time_minutes": 0
                    },
                    "unscheduled_tasks": [],
                    "recommendations": ["No tasks to schedule."]
                }
            }
        
        # Parse start time
        try:
            start_dt = datetime.strptime(start_time, "%H:%M")
        except ValueError:
            return {"status": "error", "error_message": f"Invalid start_time format: {start_time}. Use HH:MM format."}
        
        # Sort tasks by priority and deadline
        sorted_tasks = _prioritize_tasks(tasks)
        
        # Calculate total available minutes
        total_available_minutes = int(available_hours * 60)
        
        # Schedule tasks
        schedule = []
        unscheduled = []
        current_time = start_dt
        total_scheduled_minutes = 0
        total_buffer_minutes = 0
        
        for task in sorted_tasks:
            task_duration = task["duration_minutes"]
            buffer_time = int(task_duration * buffer_percentage)
            total_task_time = task_duration + buffer_time
            
            # Check if task fits in remaining time
            time_used = total_scheduled_minutes + total_task_time
            if schedule:  # Add break time if not the first task
                time_used += break_duration_minutes
            
            if time_used <= total_available_minutes:
                # Add break before this task if it's not the first
                if schedule:
                    current_time += timedelta(minutes=break_duration_minutes)
                
                # Schedule the task
                task_start = current_time
                task_end = current_time + timedelta(minutes=total_task_time)
                
                schedule.append({
                    "task_name": task["name"],
                    "start_time": task_start.strftime("%H:%M"),
                    "end_time": task_end.strftime("%H:%M"),
                    "duration_minutes": task_duration,
                    "priority": task["priority"]
                })
                
                current_time = task_end
                total_scheduled_minutes += total_task_time
                total_buffer_minutes += buffer_time
                
                # Add break time to scheduled minutes for next iteration
                if schedule:
                    total_scheduled_minutes += break_duration_minutes
            else:
                # Task doesn't fit
                remaining_minutes = total_available_minutes - total_scheduled_minutes
                unscheduled.append({
                    "name": task["name"],
                    "reason": f"Insufficient time (needs {total_task_time} min, {remaining_minutes} min remaining)"
                })
        
        # Calculate metrics
        # Adjust for the last break that wasn't actually used
        if schedule:
            actual_scheduled = total_scheduled_minutes - break_duration_minutes
        else:
            actual_scheduled = 0
            
        utilization = (actual_scheduled / total_available_minutes * 100) if total_available_minutes > 0 else 0.0
        
        metrics = {
            "total_scheduled_minutes": actual_scheduled,
            "total_available_minutes": total_available_minutes,
            "utilization_percentage": round(utilization, 2),
            "unscheduled_tasks": len(unscheduled),
            "buffer_time_minutes": total_buffer_minutes
        }
        
        # Generate recommendations
        recommendations = _generate_recommendations(
            schedule, unscheduled, metrics, available_hours
        )
        
        return {
            "status": "success",
            "result": {
                "schedule": schedule,
                "metrics": metrics,
                "unscheduled_tasks": unscheduled,
                "recommendations": recommendations
            }
        }
        
    except Exception as e:
        return {"status": "error", "error_message": f"Unexpected error during scheduling: {str(e)}"}


def _validate_inputs(
    tasks: list[dict],
    available_hours: float,
    start_time: str,
    break_duration_minutes: int,
    buffer_percentage: float
) -> str | None:
    """Validate all input parameters. Returns error message or None if valid."""
    
    # Validate available_hours
    if not isinstance(available_hours, (int, float)):
        return "available_hours must be a number"
    if available_hours < 0:
        return "available_hours must be non-negative"
    if available_hours > 24:
        return "available_hours cannot exceed 24"
    
    # Validate start_time format
    if not isinstance(start_time, str):
        return "start_time must be a string"
    if not start_time or ":" not in start_time:
        return "start_time must be in HH:MM format"
    
    # Validate break_duration_minutes
    if not isinstance(break_duration_minutes, int):
        return "break_duration_minutes must be an integer"
    if break_duration_minutes < 0:
        return "break_duration_minutes must be non-negative"
    
    # Validate buffer_percentage
    if not isinstance(buffer_percentage, (int, float)):
        return "buffer_percentage must be a number"
    if buffer_percentage < 0 or buffer_percentage > 1:
        return "buffer_percentage must be between 0 and 1"
    
    # Validate tasks
    if not isinstance(tasks, list):
        return "tasks must be a list"
    
    for i, task in enumerate(tasks):
        if not isinstance(task, dict):
            return f"Task {i} must be a dictionary"
        
        if "name" not in task:
            return f"Task {i} missing required field 'name'"
        if not isinstance(task["name"], str):
            return f"Task {i} 'name' must be a string"
        
        if "duration_minutes" not in task:
            return f"Task {i} ('{task.get('name', 'unknown')}') missing required field 'duration_minutes'"
        if not isinstance(task["duration_minutes"], int):
            return f"Task {i} ('{task['name']}') 'duration_minutes' must be an integer"
        if task["duration_minutes"] <= 0:
            return f"Task {i} ('{task['name']}') 'duration_minutes' must be positive"
        
        if "priority" not in task:
            return f"Task {i} ('{task['name']}') missing required field 'priority'"
        if task["priority"] not in ["high", "medium", "low"]:
            return f"Task {i} ('{task['name']}') 'priority' must be 'high', 'medium', or 'low'"
        
        # Validate optional deadline
        if "deadline" in task and task["deadline"]:
            try:
                datetime.strptime(task["deadline"], "%Y-%m-%d")
            except (ValueError, TypeError):
                return f"Task {i} ('{task['name']}') 'deadline' must be in YYYY-MM-DD format"
    
    return None


def _prioritize_tasks(tasks: list[dict]) -> list[dict]:
    """Sort tasks by priority (high > medium > low) and then by deadline."""
    
    priority_order = {"high": 0, "medium": 1, "low": 2}
    
    def sort_key(task: dict) -> tuple:
        priority_rank = priority_order.get(task["priority"], 3)
        
        # Parse deadline if present, otherwise use a far future date
        deadline = task.get("deadline")
        if deadline:
            try:
                deadline_dt = datetime.strptime(deadline, "%Y-%m-%d")
            except (ValueError, TypeError):
                deadline_dt = datetime.max
        else:
            deadline_dt = datetime.max
        
        return (priority_rank, deadline_dt)
    
    return sorted(tasks, key=sort_key)


def _generate_recommendations(
    schedule: list[dict],
    unscheduled: list[dict],
    metrics: dict,
    available_hours: float
) -> list[str]:
    """Generate actionable recommendations based on scheduling results."""
    
    recommendations = []
    
    if not schedule and not unscheduled:
        recommendations.append("No tasks to schedule.")
        return recommendations
    
    # Check utilization
    utilization = metrics["utilization_percentage"]
    
    if utilization > 95:
        recommendations.append("Schedule is at maximum capacity. Consider extending work hours or deferring low-priority tasks.")
    elif utilization > 80:
        recommendations.append("Schedule is heavily loaded. Limited flexibility for unexpected delays.")
    elif utilization < 50:
        recommendations.append("Low schedule utilization. Consider adding more tasks or reducing available hours.")
    else:
        recommendations.append("Schedule utilization is balanced.")
    
    # Handle unscheduled tasks
    if unscheduled:
        recommendations.append(f"{len(unscheduled)} task(s) could not be scheduled due to time constraints.")
        recommendations.append("Consider: splitting large tasks, delegating work, or extending work hours.")
        
        # Check if increasing hours slightly would help
        high_priority_unscheduled = [t for t in unscheduled if "high" in t["name"].lower()]
        if high_priority_unscheduled:
            recommendations.append("High-priority tasks remain unscheduled. Prioritize these for immediate attention.")
    
    # Buffer time feedback
    buffer_minutes = metrics["buffer_time_minutes"]
    if buffer_minutes > 0:
        recommendations.append(f"Built-in buffer time: {buffer_minutes} minutes to accommodate estimation inaccuracies.")
    
    # Task count feedback
    if len(schedule) > 12:
        recommendations.append("Large number of tasks scheduled. Consider grouping similar tasks to reduce context switching.")
    
    return recommendations
