# Generated by NeuroStack
# Vendored from platform origin: tool/pp_calculator_tools (upstream_version=platform)

"""
Generated Tools - pp_calculator_tools.py

Auto-generated tools created by the Tool Generator.
Generated on: 2024-11-01 15:22:00
Total tools: 4
"""

from typing import Dict, Any

def add(num1: float, num2: float) -> Dict[str, Any]:
    """Adds two numbers.

    Args:
        num1 (float): The first number.
        num2 (float): The second number.

    Returns:
        Dict[str, Any]: Standard return format with success, message, and data fields.
    """
    try:
        result = num1 + num2
        return {
            "success": True,
            "message": "Addition completed successfully.",
            "data": {"result": result}
        }
    except TypeError as e:
        return {
            "success": False,
            "message": f"Error: {str(e)}",
            "data": {}
        }

def subtract(num1: float, num2: float) -> Dict[str, Any]:
    """Subtracts two numbers.

    Args:
        num1 (float): The first number.
        num2 (float): The second number.

    Returns:
        Dict[str, Any]: Standard return format with success, message, and data fields.
    """
    try:
        result = num1 - num2
        return {
            "success": True,
            "message": "Subtraction completed successfully.",
            "data": {"result": result}
        }
    except TypeError as e:
        return {
            "success": False,
            "message": f"Error: {str(e)}",
            "data": {}
        }

def multiply(num1: float, num2: float) -> Dict[str, Any]:
    """Multiplies two numbers.

    Args:
        num1 (float): The first number.
        num2 (float): The second number.

    Returns:
        Dict[str, Any]: Standard return format with success, message, and data fields.
    """
    try:
        result = num1 * num2
        return {
            "success": True,
            "message": "Multiplication completed successfully.",
            "data": {"result": result}
        }
    except TypeError as e:
        return {
            "success": False,
            "message": f"Error: {str(e)}",
            "data": {}
        }

def divide(num1: float, num2: float) -> Dict[str, Any]:
    """Divides two numbers.

    Args:
        num1 (float): The first number.
        num2 (float): The second number.

    Returns:
        Dict[str, Any]: Standard return format with success, message, and data fields.
    """
    try:
        if num2 == 0:
            return {
                "success": False,
                "message": "Error: Division by zero is not allowed.",
                "data": {}
            }
        result = num1 / num2
        return {
            "success": True,
            "message": "Division completed successfully.",
            "data": {"result": result}
        }
    except TypeError as e:
        return {
            "success": False,
            "message": f"Error: {str(e)}",
            "data": {}
        }
