# Generated by NeuroStack
# Artifact: tool/process_financial_transaction.py

"""Tool for processing financial transactions (simulated high-risk operation)."""

from typing import Any, Literal


def process_financial_transaction(
    transaction_type: Literal["refund", "transfer"],
    amount: float,
    account_id: str
) -> dict[str, Any]:
    """
    Process financial transactions including refunds and transfers.
    
    **WARNING**: This operation involves money movement and has financial impact.
    
    Args:
        transaction_type: Type of transaction - either "refund" or "transfer"
        amount: Transaction amount in USD (must be positive)
        account_id: Target account identifier
        
    Returns:
        A dictionary containing:
        - status: "success" or "error"
        - transaction_id: Unique transaction identifier (on success)
        - transaction_type: Type of transaction processed
        - amount: Amount processed
        - account_id: Target account
        - timestamp: ISO timestamp of the transaction
        - message: Description of the result
        
    Raises:
        ValueError: If inputs are invalid
    """
    import json
    import secrets
    from datetime import datetime, timezone
    
    # Validate transaction type
    if transaction_type not in ["refund", "transfer"]:
        raise ValueError("transaction_type must be 'refund' or 'transfer'")
    
    # Validate amount
    if not isinstance(amount, (int, float)) or amount <= 0:
        raise ValueError("amount must be a positive number")
    
    if amount > 10000:
        return {
            "status": "error",
            "message": f"Transaction amount ${amount:.2f} exceeds maximum limit of $10,000",
            "transaction_type": transaction_type,
            "account_id": account_id,
            "timestamp": datetime.now(timezone.utc).isoformat()
        }
    
    # Validate account_id
    if not account_id or not isinstance(account_id, str):
        raise ValueError("account_id must be a non-empty string")
    
    # Simulate transaction processing
    transaction_id = secrets.token_hex(16)
    timestamp = datetime.now(timezone.utc).isoformat()
    
    return {
        "status": "success",
        "transaction_id": transaction_id,
        "transaction_type": transaction_type,
        "amount": round(amount, 2),
        "account_id": account_id,
        "timestamp": timestamp,
        "message": f"Successfully processed {transaction_type} of ${amount:.2f} for account {account_id}"
    }
