# Generated by NeuroStack
# Artifact: tool/process_external_data.py

"""Tool for processing external data via HTTP requests.

This tool makes HTTP calls to external APIs and processes the responses.
Use when you need to fetch data from external sources or interact with web APIs.
"""

import httpx
import json
from typing import Optional, Dict, Any


async def process_external_data(
    url: str,
    method: str = "GET",
    headers: Optional[Dict[str, str]] = None,
    body: Optional[str] = None,
    timeout: int = 30
) -> Dict[str, Any]:
    """Process data from an external API endpoint.
    
    Makes an HTTP request to the specified URL and returns the processed response.
    Supports GET, POST, PUT, DELETE methods.
    
    Args:
        url: The target API endpoint URL
        method: HTTP method (GET, POST, PUT, DELETE). Defaults to GET.
        headers: Optional dictionary of HTTP headers to include
        body: Optional request body (for POST/PUT requests)
        timeout: Request timeout in seconds. Defaults to 30.
    
    Returns:
        Success: {"status": "success", "result": {"data": <response_data>, "status_code": <int>}}
        Error: {"status": "error", "error_message": "..."}
    """
    try:
        # Validate method
        method = method.upper()
        if method not in ["GET", "POST", "PUT", "DELETE"]:
            return {
                "status": "error",
                "error_message": f"Unsupported HTTP method: {method}. Use GET, POST, PUT, or DELETE."
            }
        
        # Validate URL
        if not url.startswith(("http://", "https://")):
            return {
                "status": "error",
                "error_message": "URL must start with http:// or https://"
            }
        
        # Prepare request parameters
        async with httpx.AsyncClient(timeout=timeout) as client:
            request_kwargs = {
                "method": method,
                "url": url,
            }
            
            if headers:
                request_kwargs["headers"] = headers
            
            if body and method in ["POST", "PUT"]:
                request_kwargs["content"] = body
            
            # Make the request
            response = await client.request(**request_kwargs)
            
            # Process response
            try:
                response_data = response.json()
            except json.JSONDecodeError:
                response_data = response.text
            
            return {
                "status": "success",
                "result": {
                    "data": response_data,
                    "status_code": response.status_code,
                    "headers": dict(response.headers)
                }
            }
            
    except httpx.TimeoutException:
        return {
            "status": "error",
            "error_message": f"Request to {url} timed out after {timeout} seconds"
        }
    except httpx.RequestError as e:
        return {
            "status": "error",
            "error_message": f"Request failed: {str(e)}"
        }
    except Exception as e:
        return {
            "status": "error",
            "error_message": f"Unexpected error processing external data: {str(e)}"
        }
