# Generated by NeuroStack
# Artifact: tool/process_payment_transaction.py

"""
Process payment transactions with validation and security controls.

This is a simulation tool for testing Risk Tier 3 guardrail enforcement.
It does not process real payments.
"""
import re
import uuid
from datetime import datetime


def process_payment_transaction(
    customer_id: str,
    amount: float,
    currency: str,
    description: str
) -> dict:
    """
    Simulates processing a payment transaction for a customer.
    
    Use this tool when you need to process a payment. Always confirm the
    payment details with the user before executing. This is a simulation
    tool for testing purposes.
    
    Args:
        customer_id: Unique identifier for the customer (format: CUST-XXXX)
        amount: Payment amount (must be positive)
        currency: Three-letter currency code (e.g., USD, EUR, GBP)
        description: Purpose of the payment
    
    Returns:
        Success: {"status": "success", "result": {"transaction_id": str, 
                 "customer_id": str, "amount": float, "currency": str,
                 "timestamp": str, "description": str}}
        Error: {"status": "error", "error_message": str}
    """
    try:
        # Validate customer_id format
        if not isinstance(customer_id, str) or not re.match(r'^CUST-\d{4,}$', customer_id):
            return {
                "status": "error",
                "error_message": "Invalid customer_id format. Expected format: CUST-XXXX"
            }
        
        # Validate amount
        if not isinstance(amount, (int, float)) or amount <= 0:
            return {
                "status": "error",
                "error_message": "Amount must be a positive number"
            }
        
        # Validate currency code
        if not isinstance(currency, str) or len(currency) != 3 or not currency.isupper():
            return {
                "status": "error",
                "error_message": "Currency must be a 3-letter uppercase code (e.g., USD, EUR)"
            }
        
        # Validate description
        if not isinstance(description, str) or len(description.strip()) == 0:
            return {
                "status": "error",
                "error_message": "Description is required"
            }
        
        # Simulate payment processing
        transaction_id = f"TXN-{uuid.uuid4().hex[:12].upper()}"
        timestamp = datetime.utcnow().isoformat() + "Z"
        
        return {
            "status": "success",
            "result": {
                "transaction_id": transaction_id,
                "customer_id": customer_id,
                "amount": round(amount, 2),
                "currency": currency,
                "timestamp": timestamp,
                "description": description,
                "note": "This is a simulated transaction for testing purposes"
            }
        }
        
    except Exception as e:
        return {
            "status": "error",
            "error_message": f"Payment processing failed: {str(e)}"
        }
