# Generated by NeuroStack
# Vendored from platform origin: tool/search_kb_and_draft_response_tools (upstream_version=platform)

"""
Generated Tools - search_kb_and_draft_response_tools.py

Auto-generated tools created by the Tool Generator.
Generated on: 2024-02-29 17:22:00
Total tools: 1
"""

from typing import Dict, Any, List, Optional

def search_kb_and_draft_response(ticket_summary: str, ticket_description: str, kb_results: List[Dict[str, str]], customer_name: str = "Customer") -> Dict[str, Any]:
    """
    Formats a customer-facing support reply by assembling a structured draft from the inputs.
    
    Args:
        ticket_summary (str): A brief summary of the customer's issue.
        ticket_description (str): A detailed description of the customer's issue.
        kb_results (list): A list of dictionaries, where each dictionary represents a KB article with "title" and "content" keys.
        customer_name (str, optional): The name of the customer. Defaults to "Customer".
    
    Returns:
        Dict[str, Any]: Standard return format with success, message, and data fields.
                       Example: {"success": True, "message": "Draft created", "data": {"draft_response": "<full text>", "steps_count": <int>, "kb_sources": [list of title strings]}}
    """
    try:
        greeting = f"Hi {customer_name},"
        acknowledgment = f"Thank you for reaching out. We understand you're experiencing an issue with {ticket_summary}."
        
        if kb_results:
            steps = []
            kb_sources = []
            for i, article in enumerate(kb_results):
                title = article.get("title", "Untitled")
                content = article.get("content", "No content")
                steps.append(f"{i+1}. {title}: {content}")
                kb_sources.append(title)
            
            steps_text = "\n".join(steps)
            steps_count = len(steps)
            body = f"Here are some troubleshooting steps that may help:\n{steps_text}"
        
        else:
            body = "Our support team is reviewing your issue and will respond shortly."
            steps_count = 0
            kb_sources = []
        
        closing = "If these steps don't resolve your issue, please reply to this ticket."
        
        draft_response = f"{greeting}\n\n{acknowledgment}\n\n{body}\n\n{closing}"
        
        return {
            "success": True,
            "message": "Draft created",
            "data": {
                "draft_response": draft_response,
                "steps_count": steps_count,
                "kb_sources": kb_sources
            }
        }
    except Exception as e:
        return {
            "success": False,
            "message": f"Error: {str(e)}",
            "data": {}
        }
