# Generated by NeuroStack
# Vendored from platform origin: tool/threat_hunting_timeline_tools (upstream_version=platform)

"""
Threat Hunting Timeline Tools (Demo-only, local-only).

Collect investigation events, build a unified time-ordered timeline, group into 2–4 episodes,
and produce short structured episode summaries with evidence pointers.
"""

from __future__ import annotations

from datetime import timedelta
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from .threat_hunting_data_tools import _get_nested, _parse_ts, read_events, load_threat_hunting_dataset


def _timeline_shape(evt: Dict[str, Any], source_table: str) -> Dict[str, Any]:
    ts = evt.get("@timestamp")
    out = {
        "ts": ts,
        "event_id": _get_nested(evt, "event.id"),
        "event_category": _get_nested(evt, "event.category"),
        "event_action": _get_nested(evt, "event.action"),
        "event_outcome": _get_nested(evt, "event.outcome"),
        "username": _get_nested(evt, "user.name"),
        "host": _get_nested(evt, "host.name"),
        "src_ip": _get_nested(evt, "source.ip"),
        "dst_ip": _get_nested(evt, "destination.ip"),
        "process": _get_nested(evt, "process.name"),
        "command_line": _get_nested(evt, "process.command_line"),
        "resource": _get_nested(evt, "resource.id") or _get_nested(evt, "resource.name"),
        "cloud_region": _get_nested(evt, "cloud.region"),
        "correlation_id": _get_nested(evt, "correlation.id"),
        "raw_ref": {"table": source_table, "event_id": _get_nested(evt, "event.id")},
    }
    return out


def _evidence_from_table(table_path: str, event_id: str, ts: str, reason: str) -> Dict[str, Any]:
    return {
        "event_id": event_id,
        "table": table_path,
        "timestamp": ts,
        "reason_used": reason,
    }


def collect_investigation_events(
    entity_username: str,
    start_ts: str,
    end_ts: str,
    dataset_root: str = "data/threat_hunting_demo",
    expansion: Optional[Dict[str, Any]] = None,
) -> Dict[str, Any]:
    """
    Collect events relevant to the investigation:
    - Seeded by the entity (user.name)
    - Expand to hosts touched in auth events
    - Pull process/network/dns for those hosts
    - Pull cloud audit for the entity
    """
    try:
        ds = load_threat_hunting_dataset(dataset_root)
        if not ds["success"]:
            return ds
        tables = ds["data"]["tables"]

        expansion = expansion or {}
        max_hosts = int(expansion.get("max_hosts", 10))

        auth_path = tables["auth_events"]
        proc_path = tables["process_events"]
        net_path = tables["network_events"]
        dns_path = tables["dns_events"]
        cloud_path = tables["cloud_audit_events"]

        auth = read_events(auth_path, start_ts, end_ts, {"user.name": entity_username}, limit=100000)
        if not auth["success"]:
            return auth

        auth_events = auth["data"]["events"]
        touched_hosts = []
        for e in auth_events:
            h = _get_nested(e, "host.name")
            if h:
                touched_hosts.append(str(h).lower())
        host_set = sorted(list(set(touched_hosts)))[:max_hosts]

        proc_events: List[Dict[str, Any]] = []
        net_events: List[Dict[str, Any]] = []
        dns_events: List[Dict[str, Any]] = []

        # Primary: user-scoped pulls (ensures we don't miss lateral movement where host != auth host)
        p_user = read_events(proc_path, start_ts, end_ts, {"user.name": entity_username}, limit=100000)
        if p_user.get("success"):
            proc_events.extend(p_user["data"]["events"])
        n_user = read_events(net_path, start_ts, end_ts, {"user.name": entity_username}, limit=100000)
        if n_user.get("success"):
            net_events.extend(n_user["data"]["events"])
        d_user = read_events(dns_path, start_ts, end_ts, {"user.name": entity_username}, limit=100000)
        if d_user.get("success"):
            dns_events.extend(d_user["data"]["events"])

        # Secondary: host expansion (captures post-auth host activity even if user field is missing)
        for host in host_set:
            p = read_events(proc_path, start_ts, end_ts, {"host.name": host}, limit=50000)
            if p.get("success"):
                proc_events.extend(p["data"]["events"])
            n = read_events(net_path, start_ts, end_ts, {"host.name": host}, limit=50000)
            if n.get("success"):
                net_events.extend(n["data"]["events"])
            d = read_events(dns_path, start_ts, end_ts, {"host.name": host}, limit=50000)
            if d.get("success"):
                dns_events.extend(d["data"]["events"])

        cloud = read_events(cloud_path, start_ts, end_ts, {"user.name": entity_username}, limit=100000)
        cloud_events = cloud.get("data", {}).get("events", []) if cloud.get("success") else []

        # De-duplicate by event.id (across tables unlikely but safe)
        seen = set()
        all_events: List[Tuple[str, Dict[str, Any]]] = []

        def add(table: str, evts: List[Dict[str, Any]]):
            for e in evts:
                eid = _get_nested(e, "event.id")
                if not eid or eid in seen:
                    continue
                seen.add(eid)
                all_events.append((table, e))

        add(auth_path, auth_events)
        add(proc_path, proc_events)
        add(net_path, net_events)
        add(dns_path, dns_events)
        add(cloud_path, cloud_events)

        # Sort by timestamp
        all_events.sort(key=lambda t: _parse_ts(t[1]["@timestamp"]))
        
        # DEMO MODE: Cap total collected events across all queries to 5 for extreme safety
        all_events = all_events[:5]

        evidence = []
        for table, e in all_events:
            evidence.append(
                _evidence_from_table(table, _get_nested(e, "event.id"), e.get("@timestamp"), "timeline_inclusion")
            )

        return {
            "success": True,
            "message": f"Collected {len(all_events)} investigation event(s)",
            "data": {
                "entity": entity_username,
                "window": {"start_ts": start_ts, "end_ts": end_ts},
                "touched_hosts": host_set,
                "events": [{"table": table, "event": e} for table, e in all_events],
                "evidence": evidence,
            },
        }
    except Exception as e:
        return {"success": False, "message": f"Error collecting investigation events: {e}", "data": None}


def build_timeline(collected: Dict[str, Any]) -> Dict[str, Any]:
    """
    Convert collected multi-table events into a unified timeline event shape.
    """
    try:
        items = collected.get("data", {}).get("events", [])
        timeline: List[Dict[str, Any]] = []
        for item in items:
            table = item.get("table")
            evt = item.get("event") or {}
            timeline.append(_timeline_shape(evt, table))

        timeline.sort(key=lambda e: _parse_ts(e["ts"]))
        return {"success": True, "message": f"Built timeline with {len(timeline)} event(s)", "data": {"timeline": timeline}}
    except Exception as e:
        return {"success": False, "message": f"Error building timeline: {e}", "data": None}


def group_into_episodes(
    timeline_events: List[Dict[str, Any]],
    heuristics: Optional[Dict[str, Any]] = None,
) -> Dict[str, Any]:
    """
    Group timeline events into 2–4 episodes using deterministic heuristics:
    - new episode if gap > 25 minutes
    - or if category transitions (authentication -> process -> cloud) after a smaller gap
    """
    try:
        heuristics = heuristics or {}
        gap_minutes = int(heuristics.get("gap_minutes", 25))
        max_episodes = int(heuristics.get("max_episodes", 4))

        if not timeline_events:
            return {"success": True, "message": "No timeline events to group", "data": {"episodes": []}}

        events = sorted(timeline_events, key=lambda e: _parse_ts(e["ts"]))
        episodes: List[List[Dict[str, Any]]] = []
        current: List[Dict[str, Any]] = [events[0]]

        def is_transition(prev_cat: Optional[str], next_cat: Optional[str]) -> bool:
            if not prev_cat or not next_cat:
                return False
            # A small transition map for demo readability
            transitions = {
                ("authentication", "process"),
                ("process", "network"),
                ("network", "cloud"),
                ("authentication", "cloud"),
            }
            return (str(prev_cat).lower(), str(next_cat).lower()) in transitions

        for prev, nxt in zip(events, events[1:]):
            prev_dt = _parse_ts(prev["ts"])
            nxt_dt = _parse_ts(nxt["ts"])
            gap = (nxt_dt - prev_dt)
            prev_cat = (prev.get("event_category") or "").lower()
            nxt_cat = (nxt.get("event_category") or "").lower()

            if gap > timedelta(minutes=gap_minutes) or (gap > timedelta(minutes=8) and is_transition(prev_cat, nxt_cat)):
                episodes.append(current)
                current = [nxt]
            else:
                current.append(nxt)
        episodes.append(current)

        # Compress if too many episodes: merge tail episodes into last bucket
        if len(episodes) > max_episodes:
            head = episodes[: max_episodes - 1]
            tail = []
            for ep in episodes[max_episodes - 1 :]:
                tail.extend(ep)
            head.append(tail)
            episodes = head

        out = []
        for idx, ep in enumerate(episodes, start=1):
            ep_sorted = sorted(ep, key=lambda e: _parse_ts(e["ts"]))
            start_ts = ep_sorted[0]["ts"]
            end_ts = ep_sorted[-1]["ts"]
            # Pick 3–6 key events: first, last, and up to 4 "high-signal"
            key = [ep_sorted[0]]
            # high-signal: cloud access, powershell, dns exfil domain
            for ev in ep_sorted[1:-1]:
                if len(key) >= 5:
                    break
                cat = (ev.get("event_category") or "").lower()
                proc = (ev.get("process") or "").lower()
                res = (ev.get("resource") or "").lower()
                if cat in {"cloud", "process", "dns"} or "powershell" in proc or "exfil" in res:
                    key.append(ev)
            if ep_sorted[-1] != ep_sorted[0] and len(key) < 6:
                key.append(ep_sorted[-1])
            key = key[:6]

            entities_touched = sorted(
                list(
                    {
                        x
                        for x in [
                            *(ev.get("host") for ev in ep_sorted),
                            *(ev.get("resource") for ev in ep_sorted),
                            *(ev.get("src_ip") for ev in ep_sorted),
                            *(ev.get("dst_ip") for ev in ep_sorted),
                        ]
                        if x
                    }
                )
            )

            out.append(
                {
                    "episode_id": f"E{idx}",
                    "title": "",  # to be filled by summarize_episode or LLM
                    "start_ts": start_ts,
                    "end_ts": end_ts,
                    "key_events": key,
                    "entities_touched": entities_touched,
                }
            )

        return {"success": True, "message": f"Grouped into {len(out)} episode(s)", "data": {"episodes": out}}
    except Exception as e:
        return {"success": False, "message": f"Error grouping episodes: {e}", "data": None}


def summarize_episode(episode: Dict[str, Any]) -> Dict[str, Any]:
    """
    Create a short, analyst-style episode title and summary based on key events.
    """
    try:
        key_events = episode.get("key_events", [])
        cats = [str(e.get("event_category", "")).lower() for e in key_events]
        has_auth = "authentication" in cats
        has_proc = "process" in cats
        has_cloud = "cloud" in cats
        has_dns = "dns" in cats

        title = "Investigation activity"
        if has_auth and not (has_proc or has_cloud):
            title = "Initial anomalous access using the service account"
        elif has_auth and has_proc:
            title = "Post-authentication execution and host activity"
        elif has_proc and has_cloud:
            title = "Host activity followed by cloud access"
        elif has_cloud:
            title = "Cloud access burst consistent with collection"
        elif has_dns:
            title = "DNS activity potentially supporting exfiltration"

        # Build 1–2 sentence summary with concrete nouns
        first = key_events[0] if key_events else {}
        user = first.get("username") or "unknown"
        hosts = [e.get("host") for e in key_events if e.get("host")]
        resources = [e.get("resource") for e in key_events if e.get("resource")]

        summary = f"Observed activity for {user}"
        if hosts:
            summary += f" involving host(s) {', '.join(sorted(set(hosts)))}"
        if resources:
            summary += f" and resource(s) {', '.join(sorted(set(resources)))}"
        summary += "."

        ep_out = dict(episode)
        ep_out["title"] = title
        ep_out["summary"] = summary

        return {"success": True, "message": "Summarized episode", "data": {"episode": ep_out}}
    except Exception as e:
        return {"success": False, "message": f"Error summarizing episode: {e}", "data": None}
