# Generated by NeuroStack
# Artifact: tool/write_formatted_blog.py

"""
Blog writing tool that formats content with summary and keywords.

This tool takes either raw text or a URL and creates a well-formatted blog post
with automatic summarization and keyword extraction in JSON format.
"""

import httpx
from bs4 import BeautifulSoup
import yake
from datetime import datetime
from collections import defaultdict
import re
from typing import Optional


async def write_formatted_blog(
    content: Optional[str] = None,
    url: Optional[str] = None,
    topic: Optional[str] = None,
    summary_sentences: int = 3,
    num_keywords: int = 5
) -> dict:
    """
    Creates a formatted blog post with summary and keywords from content or URL.
    
    Use this tool when you need to transform raw content or web articles into
    structured blog posts with automatic summarization and keyword extraction.
    
    Args:
        content: Raw text content to format into a blog post (optional if url provided)
        url: URL to fetch content from (optional if content provided)
        topic: Custom title for the blog post (optional, auto-extracted if not provided)
        summary_sentences: Number of sentences for the summary (default: 3)
        num_keywords: Number of keywords to extract (default: 5)
    
    Returns:
        Success dict with:
        {
            "status": "success",
            "result": {
                "title": str,
                "summary": str,
                "keywords": list[str],
                "formatted_content": {
                    "title": str,
                    "summary": str,
                    "keywords": list[str],
                    "content": str
                },
                "metadata": {
                    "word_count": int,
                    "source": str,
                    "timestamp": str
                }
            }
        }
        
        Error dict with:
        {
            "status": "error",
            "error_message": str
        }
    """
    
    try:
        # Input validation
        if not content and not url:
            return {
                "status": "error",
                "error_message": "Either 'content' or 'url' must be provided"
            }
        
        if summary_sentences < 1:
            return {
                "status": "error",
                "error_message": "summary_sentences must be at least 1"
            }
        
        if num_keywords < 1:
            return {
                "status": "error",
                "error_message": "num_keywords must be at least 1"
            }
        
        # Fetch content from URL if provided
        title = topic
        source = "provided_text"
        
        if url:
            # Validate URL scheme
            if not url.startswith(('http://', 'https://')):
                return {
                    "status": "error",
                    "error_message": "URL must start with http:// or https://"
                }
            
            try:
                async with httpx.AsyncClient(timeout=httpx.Timeout(10.0)) as client:
                    response = await client.get(url)
                    response.raise_for_status()
                    
                    # Check content length (500KB limit)
                    content_length = len(response.content)
                    if content_length > 500 * 1024:
                        return {
                            "status": "error",
                            "error_message": f"Content too large: {content_length} bytes (max 500KB)"
                        }
                    
                    # Parse HTML
                    soup = BeautifulSoup(response.text, 'html.parser')
                    
                    # Extract title if not provided
                    if not title:
                        title_tag = soup.find('title')
                        if title_tag:
                            title = title_tag.get_text().strip()
                        else:
                            # Try h1 as fallback
                            h1_tag = soup.find('h1')
                            title = h1_tag.get_text().strip() if h1_tag else "Untitled Blog Post"
                    
                    # Extract main content
                    # Remove script and style elements
                    for script in soup(["script", "style", "nav", "footer", "header"]):
                        script.decompose()
                    
                    # Get text from paragraphs
                    paragraphs = soup.find_all('p')
                    if paragraphs:
                        content = '\n\n'.join([p.get_text().strip() for p in paragraphs if p.get_text().strip()])
                    else:
                        # Fallback to body text
                        body = soup.find('body')
                        content = body.get_text('\n', strip=True) if body else soup.get_text('\n', strip=True)
                    
                    source = url
                    
            except httpx.TimeoutException:
                return {
                    "status": "error",
                    "error_message": f"Request timed out after 10 seconds for URL: {url}"
                }
            except httpx.ConnectError as e:
                return {
                    "status": "error",
                    "error_message": f"Connection error: Unable to connect to {url}"
                }
            except httpx.HTTPStatusError as e:
                return {
                    "status": "error",
                    "error_message": f"HTTP error {e.response.status_code} for URL: {url}"
                }
            except httpx.RequestError as e:
                return {
                    "status": "error",
                    "error_message": f"Request error: {str(e)}"
                }
        
        # Validate we have content
        if not content or not content.strip():
            return {
                "status": "error",
                "error_message": "No usable content found"
            }
        
        # Clean up whitespace
        content = re.sub(r'\s+', ' ', content).strip()
        
        # Use topic as title if provided, otherwise try to generate from content
        if not title:
            # Use first sentence or first 60 characters as title
            first_sentence = content.split('.')[0].strip()
            title = first_sentence[:60] + ('...' if len(first_sentence) > 60 else '')
        
        # Tokenize into sentences for summarization
        sentences = _tokenize_sentences(content)
        
        if len(sentences) == 0:
            return {
                "status": "error",
                "error_message": "Could not extract sentences from content"
            }
        
        # Generate extractive summary
        summary = _generate_summary(sentences, content, min(summary_sentences, len(sentences)))
        
        # Extract keywords using YAKE
        keywords = _extract_keywords(content, num_keywords)
        
        # Format the blog post as JSON structure
        formatted_content = _format_blog_post(title, summary, keywords, content)
        
        # Calculate metadata
        word_count = len(content.split())
        timestamp = datetime.utcnow().isoformat() + 'Z'
        
        return {
            "status": "success",
            "result": {
                "title": title,
                "summary": summary,
                "keywords": keywords,
                "formatted_content": formatted_content,
                "metadata": {
                    "word_count": word_count,
                    "source": source,
                    "timestamp": timestamp
                }
            }
        }
        
    except Exception as e:
        return {
            "status": "error",
            "error_message": f"Unexpected error: {str(e)}"
        }


def _tokenize_sentences(text: str) -> list:
    """Simple sentence tokenizer."""
    # Split on period, exclamation, or question mark followed by space or end
    sentences = re.split(r'(?<=[.!?])\s+', text)
    return [s.strip() for s in sentences if s.strip() and len(s.strip()) > 10]


def _generate_summary(sentences: list, full_text: str, num_sentences: int) -> str:
    """Generate extractive summary using frequency-based sentence scoring."""
    # Tokenize words and calculate frequency
    words = re.findall(r'\b[a-z]{3,}\b', full_text.lower())
    
    # Common stopwords to ignore
    stopwords = {
        'the', 'be', 'to', 'of', 'and', 'a', 'in', 'that', 'have', 'i',
        'it', 'for', 'not', 'on', 'with', 'he', 'as', 'you', 'do', 'at',
        'this', 'but', 'his', 'by', 'from', 'they', 'we', 'say', 'her', 'she',
        'or', 'an', 'will', 'my', 'one', 'all', 'would', 'there', 'their',
        'what', 'so', 'up', 'out', 'if', 'about', 'who', 'get', 'which', 'go',
        'me', 'when', 'make', 'can', 'like', 'time', 'no', 'just', 'him', 'know',
        'take', 'people', 'into', 'year', 'your', 'good', 'some', 'could', 'them',
        'see', 'other', 'than', 'then', 'now', 'look', 'only', 'come', 'its', 'over',
        'think', 'also', 'back', 'after', 'use', 'two', 'how', 'our', 'work',
        'first', 'well', 'way', 'even', 'new', 'want', 'because', 'any', 'these',
        'give', 'day', 'most', 'us', 'is', 'was', 'are', 'been', 'has', 'had',
        'were', 'said', 'did', 'having', 'may', 'should', 'being'
    }
    
    # Calculate word frequency
    word_freq = defaultdict(int)
    for word in words:
        if word not in stopwords:
            word_freq[word] += 1
    
    # Score sentences based on word frequency
    sentence_scores = []
    for idx, sentence in enumerate(sentences):
        score = 0
        sentence_words = re.findall(r'\b[a-z]{3,}\b', sentence.lower())
        for word in sentence_words:
            if word in word_freq:
                score += word_freq[word]
        
        # Normalize by sentence length to avoid bias toward long sentences
        if len(sentence_words) > 0:
            score = score / len(sentence_words)
        
        sentence_scores.append((idx, score, sentence))
    
    # Sort by score and get top sentences
    sentence_scores.sort(key=lambda x: x[1], reverse=True)
    top_sentences = sentence_scores[:num_sentences]
    
    # Sort selected sentences by original order
    top_sentences.sort(key=lambda x: x[0])
    
    # Combine into summary
    summary = ' '.join([s[2] for s in top_sentences])
    return summary


def _extract_keywords(text: str, num_keywords: int) -> list:
    """Extract keywords using YAKE algorithm."""
    try:
        kw_extractor = yake.KeywordExtractor(
            lan="en",
            n=3,  # Max n-gram size
            dedupLim=0.7,  # Deduplication threshold
            top=num_keywords,
            features=None
        )
        
        keywords_with_scores = kw_extractor.extract_keywords(text)
        # YAKE returns (keyword, score) tuples - lower score is better
        keywords = [kw[0] for kw in keywords_with_scores]
        return keywords
        
    except Exception as e:
        # Fallback to simple frequency-based keywords if YAKE fails
        words = re.findall(r'\b[a-z]{4,}\b', text.lower())
        word_freq = defaultdict(int)
        
        stopwords = {
            'the', 'be', 'to', 'of', 'and', 'a', 'in', 'that', 'have', 'i',
            'it', 'for', 'not', 'on', 'with', 'he', 'as', 'you', 'do', 'at',
            'this', 'but', 'his', 'by', 'from', 'they', 'we', 'say', 'her', 'she',
            'or', 'an', 'will', 'my', 'one', 'all', 'would', 'there', 'their'
        }
        
        for word in words:
            if word not in stopwords:
                word_freq[word] += 1
        
        sorted_words = sorted(word_freq.items(), key=lambda x: x[1], reverse=True)
        return [word for word, freq in sorted_words[:num_keywords]]


def _format_blog_post(title: str, summary: str, keywords: list, content: str) -> dict:
    """Format content as a JSON-structured blog post."""
    return {
        "title": title,
        "summary": summary,
        "keywords": keywords,
        "content": content
    }
