# Generated by NeuroStack
# Vendored from platform origin: agent/customer_support_agent (upstream_version=platform)

"""customer_support_agent using Google ADK."""
from __future__ import annotations
from google.adk import Agent
from google.genai import types
import importlib.util as _ilu
import pathlib as _pl
_spec_rel_prompt = _ilu.spec_from_file_location(
    'prompt',
    _pl.Path(__file__).parent / 'prompt.py',
)
_mod_rel_prompt = _ilu.module_from_spec(_spec_rel_prompt)
_spec_rel_prompt.loader.exec_module(_mod_rel_prompt)

SYSTEM_PROMPT = _mod_rel_prompt.SYSTEM_PROMPT
def create_customer_support_agent_agent() -> Agent:
    return Agent(
        name="customer_support_agent",
        model='bedrock/us.anthropic.claude-sonnet-4-5-20250929-v1:0',
        description="Agent for handling customer refunds and complaints.",
        instruction=SYSTEM_PROMPT,
        tools=[],
        generate_content_config=types.GenerateContentConfig(
            safety_settings=[types.SafetySetting(
                category=types.HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT,
                threshold=types.HarmBlockThreshold.OFF,
            )]
        ),
    )

customer_support_agent_agent = create_customer_support_agent_agent()
root_agent = customer_support_agent_agent
