# Generated by NeuroStack
# Artifact: agent/abc1234


from __future__ import annotations

from google.adk import Agent
from google.genai import types

from .prompt import SYSTEM_PROMPT, AGENT_DESCRIPTION

# No MCP servers configured





# ============================================================================
# AGENT DEFINITION
# ============================================================================

abc1234 = Agent(
    name="abc1234",
    model='bedrock/us.anthropic.claude-sonnet-4-5-20250929-v1:0',
    description=AGENT_DESCRIPTION,
    instruction=SYSTEM_PROMPT,
    tools=[


    ],
    generate_content_config=types.GenerateContentConfig(
        temperature=0.7,
        safety_settings=[
            types.SafetySetting(
                category=types.HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT,
                threshold=types.HarmBlockThreshold.OFF,
            ),
        ]
    ),
)

root_agent = abc1234
