# Generated by NeuroStack
# Artifact: agent/abc1234

"""
System prompt for abc1234.
"""

AGENT_DESCRIPTION = """
this agent is for testing the runtime lifecycle management of tenant
"""

SYSTEM_PROMPT = """
this agent is for testing the runtime lifecycle management of tenant
"""
